### ISSUE TITLE
Decentralized Exchange v1

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#10]
# Description
A Jumpscale friendly deployment and delivery of a decentralized exchange where atomicswaps can be executed.
For this version we aim to support BTC and TFT but supporting other coins/blockchains should be a design/implementation consideration.  

# Goal
We want to allow users to deploy nodes the has all the required software and configurations to participate in a decentralized exchange.
We also need to provide simple and usable APIs to start an exchange operation between BTC and TFT.

Eventually we want to meet build the system described here: [Atomic Exchange](https://github.com/rivine/AtomicExchange/blob/master/AtomicExchange.Docs/ArchitectureVersion1.md) 

# Requirement 
To build the solution we need:
### Electrum JS9 Integration
- Prefab to install electrum wallet [Electrum Wallet](https://github.com/spesmilo/electrum)
- Flist for electrum wallet
- Client integration for js9 ( we need to be able to use a jumpscale client to communicate with the electrum wallet )
- Atomicswap using electrum client*

### Atomicswap SAL
The current atomicswap SAL in jumpscale is not decentralized. Even though the nodes are running separately, but parties have to trust the node running the SAL to orchestrate the atomicswap process.

We need to improve this by:
- Implement JSON-RPC/gRPC server for initiator and participants
- Each server should use the corresponding light wallet to execute the different atomicswap operations
- SAL should be only a starting point to get connection to both servers. 
- Create prefab modules to install the servers
- Create an flist for the server binary

### 0-Robot Integration
To be able to deploy the above solutions on top of our ThreeFold grid, we will need to use [0-robot](https://github.com/zero-os/0-robot)

To manage that we need 0-robot templates to:
- Deploy containers/vms on top of ZOS nodes that start from new flists
- Start the different services with the appropriate configurations
- Trigger Atomicswap via the jumpscale SAL

# Deliverables
- Prefab to install Electrum binary
- Flist including electrum binary
- Electrum client library in jumpscale (j.clients.blockchain.electrum) that support atomicswap
- Prefab to install atomicswap RPC servers
- Flist for the atomicswap RPC server
- 0-robot templates
- Documentation for how to use each of the above.
- Unit Tests (when applicable)

# Code
- [Jumpscale libs](https://github.com/Jumpscale/lib9) Should contain all the client library code.
- [Jumpscale prefab](https://github.com/Jumpscale/prefab9) Should contain all the prefab modules.
- [Jumpscale sandbox](https://github.com/Jumpscale/sandbox) Should contain all the sandboxing (creating flists) scripts
- [0-templates](https://github.com/Jumpscale/atomic_exchange) Should contain all 0-templates relating to the exchange

# Stakeholders
+ Rob Van Mieghem (@robvanmieghem); Rivine code base maintainer and bockchain general advice.
+ Glen De Cauwsemaecker (@glendc); Rivine code base maintainer and bockchain general advice.
+ Kristof De Spiegeleer (@despiegk); Feature specific questions
+ Jonas Delrue (@jdelrue); Feature questions and usage questions.

# Related feature requests & bugs
- [x] Client Integration of electrum wallet in JS9 [#339] (https://github.com/Jumpscale/lib9/issues/339)
- [ ] Atomicswap support for electrum wallet [#340] (https://github.com/Jumpscale/lib9/issues/340)
- [x] Electrum prefab module [#202](https://github.com/Jumpscale/prefab9/issues/202)
- [ ] Atomicswap RPC server in JS9 [#341](https://github.com/Jumpscale/lib9/issues/341)
- [x] Create Electrum flist and update cryptosandbox flist [#12](https://github.com/Jumpscale/sandbox/issues/12)
- [ ] 0-Robot templates for deployments [#1](https://github.com/Jumpscale/atomic_exchange/issues/1)

**Comment by GlenDC** [comment]
Why is this closed, adding a reason would be nice.
