### ISSUE TITLE
rename jumpscale repos 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1005]
## reasoning

- `js-` prefix confuses people and make them think it's a javascript library
- ng reflects a bad reputation on previous version
- js-sdk the sdk is a software development kit but for what? clearly not the grid because it has many many other libraries.

## phase 1
- [x] archive old jsx repos
- [ ] rename js-grid to tfgrid_sdk
- [x] rename js-ansible-modules to jumpscale_ansible

## phase 2
- [ ] better name for js-ng,  current suggestion: jumpscale_core  
- [ ] better name of js-sdk (as it has  more functionality than needed for development around the grid e.g sendgrid, s3, digital ocean..., current suggestion is tfgrid_extensions or  tfgrid_ext (prefer a better name)

**Comment by despiegk** [comment]
needs to be used for tfgrid 2.5

kristof will already use now to start creating the documentation for TFGRID_SDK

**Comment by rkhamis** [comment]
I've archived old repos
