### ISSUE TITLE
Grid launch phase 1

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#101]
### Product available for reservation

- Virtual 0-OS
- S3 exposed over webgateway

### To be verified

- [x] VM templates
  - https://github.com/threefoldtech/0-templates/tree/development/templates/vm
  - https://github.com/threefoldtech/0-templates/tree/development/templates/dm_vm
- [x] vdisk template: https://github.com/threefoldtech/0-templates/tree/development/templates/vdisk
- [x] zerodb template: https://github.com/threefoldtech/0-templates/tree/development/templates/zerodb
- [x] namespace template: https://github.com/threefoldtech/0-templates/tree/development/templates/namespace
- [x] Flist for 0-OS VM
- [ ] Zerotier client service should not be mandatory for a `vm_dm` when it gets a public zt network
- [x] 0-OS / 0-robot on reserved vm can't be reached (but vnc can): turns out we were using an flist of the development branch of 0-OS for the VM. Using a build from master works.
- [x] Make sure incomming transactions aren't timelocked

### To be developed

- [x] Reservation format
- [x] Daemon that watch tfchain for new blocks containing reservation information
- [x] Capacity planning (maybe not needed)
- [x] ~Glue code between centralized 0-robot and reservation watcher~ Watcher has been implemented as a 0-robot template
- [ ] [Solution for vdisk never that is nerver scrubbed](https://github.com/threefoldtech/0-db/issues/35#issuecomment-450144443)
- [x] Tools to send email to user after deployment is done
- [x] Support s3 in reservation service
- [x] Refund in case reservation fails
- [x] [Template to configure network for lochristi's farm](https://github.com/threefoldtech/home/issues/130)
- [x] Encryption for the transaction data
  - [x] [light wallet part](https://github.com/threefoldfoundation/tfchain/issues/315) : not required anymore, reservations will be created with JSX
  - [x] [brid broker part](https://github.com/threefoldtech/grid_broker/issues/2)
- [x] [Reservation code in tfchain client](https://github.com/threefoldtech/jumpscaleX/issues/214)
- [x] [crypto primitives in js9](https://github.com/threefoldtech/grid_broker/issues/3)
- [x] [new reservation flow using notary in the broker](https://github.com/threefoldtech/grid_broker/issues/4)
- [x] [Expose private keys in tfchain client for an address](https://github.com/threefoldtech/jumpscale_lib/issues/287)
- [x] [ability to fetch a 3bot record](https://github.com/threefoldtech/jumpscale_lib/issues/288)
- [x] [Allow both farm id and node id for reserving a vm](https://github.com/threefoldtech/grid_broker/issues/7)
- [ ] [notary home page](https://github.com/threefoldtech/digitalmeX/issues/33)

### Deployment:
- [x] Choose where we're going to run the grid_broker and notary
- [x] Deploy Grid broker
- [x] Deploy notary
- [x] Register threebot on tfchain for the grid broker
- [x] Create a wallet for the grid broker

### Documentation
- [x] [Full tutorial how to create a tfchain wallet and register a threebot using jsx tfchain client](https://github.com/threefoldtech/grid_broker/issues/5)
- [x] [Full tutorial how to reserve some capacity using jsx tfchain client](https://github.com/threefoldtech/grid_broker/issues/6)
- [ ] [Example how to use your virtual 0-OS](https://github.com/threefoldfoundation/info_grid/issues/67)

### Open questions:
- [ ] [Should the grid broker wait X number of verification of a block before processing a reservation](https://github.com/threefoldtech/grid_broker/issues/8)

![reservation_flow](https://user-images.githubusercontent.com/303164/53555622-967a7980-3b42-11e9-8e9c-38f9ee362686.png)

**Comment by zaibon** [comment]
I started to work on the templates for the central robots. 
I've created a new template repo to host these templates at https://github.com/threefoldtech/grid_broker

In there I have the basic logic to watch the transaction coming in for a specific wallet.
when there are proper data attached to the transaction, the creation of a reservation is trigger and some workload is deployed.

So far so good. There is still quite some logic to be done but as a first POC things seems to work ok.

One thing I would like to disscuss more is the reservation format to put in the transaction.
@delandtj @GlenDC @LeeSmet @robvanmieghem if you guys have some idea how we could make that user friendly. Knowing that the only client that support to send trancastion with data are the jumpscale of tfchainc. So would be cool to have a format to use easy for both client.

**Comment by zaibon** [comment]
Found out that the 0-OS vm don't reserve the first disk for the filesystem cache. We'll need to investigate why cause without that, the vm just eat all the memory of the host

**Comment by zaibon** [comment]
Regarding the reservation format, If we just use command like this for the tfchainc client:
` tfchainc wallet send coins --data "$(cat data.json)" addr_hash 1`
where `data.json` contains the properly formatted reservation data, this stays easy enough to use for anyone. So this means I'm not really block on the format as long as I stay in the 83 bytes limitation

**Comment by zaibon** [comment]
Preview of the documentation regarding reservation:

# Threefold grid broker

During the fist beta phase of the public launch of the TF grid, beta tester will be able to reserve 2 kind of workload on the grid.

- Zero-OS virtual machines
- S3 archive storage instances

## How to make a reservation

The reservation is done by sending some TFT to the specific address with some metadata attached to the transaction.

Example how to reserve a virtual Zero-OS:
1. make sure you have a wallet on the testnet network
2. create a file `data.json` that will contains the decription of what you want to reserve
```json
{"type":"vm", "size":1, "email": "user1@mailinator.com"}
```
3. send some money to `019bc85e0d710d928f163cbe9bf9f4911462488468ab66b758e178ea7ef978992fc203130127b7` and attachd the content of `data.json` into the transaction

```
# if needed, unlock you wallet
tfchainc wallet unlock
# send the TFT
tfchainc wallet send coins --data "$(cat data.json)" 019bc85e0d710d928f163cbe9bf9f4911462488468ab66b758e178ea7ef978992fc203130127b7 1
```

### Amount of TFT for each type of reservation:
|type|size|amount| CPU | Memory | Storage   |
| -- | --| --    | --  | --     | --     |
| vm | 1 | 1     | 1   | 2GiB   | 10 GiB |
| vm | 2 | 4     | 2   | 4GiB   | 40 GiB |
| s3 | 1 | 10    |     |        | 50 GiB |
| s3 | 2 | 40    |     |        | 100 GiB|

**Comment by LeeSmet** [comment]
Small remark about the `$(cat data.json)`, this will include any whitespace/newlince chars which are included by the user, so it might bloat the data beyond the allowed size. Also, there is no guarantee it will be valid json, which might cause issues when it gets parsed. And if it fails to parse as valid json, what happens with your funds?

**Comment by LeeSmet** [comment]
Given that the data we sent in the transaction is public, and for now it will essentially contain personal information (i.e. email address), it might also be worth it to encrypt said data. We already have keys for asymmetric encryption, and afaik there is no harm in sharing the public key instead of its hash. A client can then use a pubkey to encrypt the data, and then hash it to actually send the funds. On the receiving end, you could implement a simple function which tries to decrypt data on a transaction using the private key of the address.

**Comment by zaibon** [comment]
@LeeSmet this is actually a very good idea and it match with how things will work in the Future once we have the 3bots.
Since the 3bots are supposed to be registered on the blockchain and their public key published there. I think it is indeed how we should approach the problem

**Comment by LeeSmet** [comment]
For the reservation format I'm thinking something like the following:

1 byte for the type
1 byte for the size
MD5 of the IYO organization of the farm on which to deploy -> 16 bytes
email address (possibly base64 decoded with a modified charset to allow the `@` character)

IYO org and email address will be dropped once 3bot comes into production.

Type and size could be further compressed to take up only 1 byte between them

If we go with the encryption, taking into account the fact that most encryption schemes operate on 16 byte blocks, we have 62 bytes for the email address, a reverse base64 goes from 4 chars to 3 bytes, which means it could fit 80 bytes at most

Some small tests with gzip for the email address indicate that even on the best compression lvl, we get about a 40% overhead due to the gzip header and the small input size, so this does not seem like a viable option

**Comment by zaibon** [comment]
Updated the reservation flow schema in the first comment to include the notary

**Comment by zaibon** [comment]
Got block today on : https://github.com/threefoldtech/digitalmeX/issues/27

**Comment by zaibon** [comment]
All 3 blocking issues are solved now.

**Comment by zaibon** [comment]
New blocking issue: https://github.com/threefoldtech/digitalmeX/issues/31

**Comment by zaibon** [comment]
So we're still block on https://github.com/threefoldtech/digitalmeX/issues/31
This means we won't make it in time. Delivery for this was supposed to be tomorrow.
I guess escalation will be required...
