### ISSUE TITLE
VDC: marketplace solutions to support threefold connect 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1015]
- [x] zeroci
- [ ] peertube https://github.com/threefoldtech/tf-peertube/issues/1
- [ ] mattermost https://github.com/threefoldtech/tf-mattermost/issues/1
- [ ] gitea  https://github.com/threefoldtech/tf-gitea/issues/12
- [ ] cryptpad  https://github.com/threefoldtech/tf-cryptpad/issues/1
- [ ] discourse https://github.com/threefoldtech/tf-discourse/issues/1
- [ ] taiga
- [ ] monitoring stack? (don't think that should be included)

## phase 1
for each of the solutions
- [ ] prepare a fork
- [ ] prepare the build pipeline (build pipelines don't work on forks on github)
- [ ] prepare the helm charts
- [ ] make sure VDC marketplace works against the forked solutions
- [ ] integrate threefold connect (should be a button to loging with threefold connect that starts the auth flow) + callback endpoint that creates the users -how do we deal with different roles?- if these solutions are exposed on the public internet?
- [ ] use the current [oauth proxy](https://oauth.threefold.io) 

## phase 2
- run [oauth proxy](https://github.com/threefoldtech/oauth-proxy) per each VDC and allow that to be used for all of the solutions

note: this issue doesn't address anything related to mobile/desktop apps for the solutions, it'd be only usable from the web browser
