### ISSUE TITLE
testplan agreed upon for 2.7.1 + make visible for community

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1040]
- we are working to do the final tests on 2.7 but as part of this process we need to agree on scope of testing more formally

## TODO

- [ ] put in cloud wiki the link to the testplan and how to look at result
- [ ] do a review of the testplan with e.g. Kristof, ...
- [ ] look at test results, how far did we get and see if we can do all in timing of roadmap
- [ ] make sure test plan can be consulted by everyone (if needed create generic test user for read only access)

**Comment by weynandkuijpers** [comment]
Testplan to be create and published (also in testlodge)

**Comment by xmonader** [comment]
What is the status of this one? I see the issue in verification, but no items are checked?

**Comment by sasha-astiadi** [comment]
new issue on foundation
