### ISSUE TITLE
Pricing Policy TFGrid 2.8 for Farming 3.0 (June 8)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1041]
# Pricing Policy TF Grid 2.8

## burning

- [x] need ability to burn tokens, can be done by explorer code

### When capacity bought by Certified Sales Channel

We expect most of the business for next 6 months to come through our certified sales channels

- [x] 25% of capacity bought through explorer 2.7 using TFT needs to be burned
- [x] 10% of fee to farmer
- [x] 10% of fee to TFFoundation (promotion_wallet_foundation)
- [x] the remainder goes to certified sales channel

### When capacity bought by Farmer itself

- [x] 25% of capacity bought through explorer 2.7 using TFT needs to be burned
- [x] 10% of fee to farmer
- [x] 5% of fee to TFFoundation
- [x] 60% of fee to farmer

This basically means farmer gets rewarded to also sell his capacity.

### When capacity bought by any Grid User

We expect this to be very small in beginning

- [x] 40% of capacity bought through explorer 2.7 using TFT needs to be burned
- [x] 10% of fee to farmer
- [x] 10% of fee to TFFoundation
- [x] the remainder goes to promotion pool as held by wisdom council to promote future sales

Details see: https://wiki.threefold.io/#/farming_logic3_tftflow or https://wiki.threefold.io/#/farming_logic3

## Pricing

implement pricing as mentioned in:

see https://wiki.threefold.io/#/cloud__tfgrid_pricing_2

## TODO

- these TFT flows need to be implemented in explorer as used on TFGrid 2.8

## Remarks

- [wallets wisdom council / foundation](https://wiki.threefold.io/#/threefold_foundation_wallets)

**Comment by xmonader** [comment]
this may require investigating casper or most likely parity

**Comment by LeeSmet** [comment]
This can be implemented in the current explorer (on stellar). The part for splitting the payment is actually already there, but it needs to be modified to identify the relationship between the buyer and the farmer to choose the correct policy

**Comment by muhamadazmy** [comment]
Q: what is a Certified Sales Channel?

**Comment by muhamadazmy** [comment]
Need clarification on `the remainder goes to promotion pool as held by wisdom council to promote future sales`

**Comment by sasha-astiadi** [comment]
will think if documentation is needed

**Comment by muhamadazmy** [comment]
Code was tested (already deployed on devnet), we can deploy this to testnet (and main-net) once we confirm that the percentage in the issue are 100% correct.
