### ISSUE TITLE
POC- Quantum Safe Storage System 0.9(June 15)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1044]
https://secure.threefold.tech/code/#/2/code/edit/B+gwgS24mPzAIMGMDqmlDjs-/

It should be self-contained, e.g all of the interaction with the grid to be done from the binary itself. also what happens if the ZDB pool(s) fail to extend for any reason? or if the farm itself goes down? is the deployment strategy across farms or against multiple nodes in the same farm? Should we on ZOS level only delete ZDB workloads on direct decommission calls from the user and leave it if its pool is out of units for a couple of days just in case?

## User Stories type_story
- [x] 0-STORV2 : explorer + stellar wallet client https://github.com/threefoldtech/0-stor_v2/issues/37
- [x] 0-STORV2 : auto-topup for pools https://github.com/threefoldtech/0-stor_v2/issues/54
- [x] 0-STORV2 : monitoring features? question here -current status and what is still needed to be done-
https://github.com/threefoldtech/quantum-storage/issues/13
- [ ] <s>0-DB: protection of ZDBs https://github.com/threefoldtech/quantum-storage/issues/12 </s>

aim is to have on testnet ASAP and production-ready by the 1st of July

## Improvements

- [x] metadata stored in 4 ZDB (2+2)
    - [x] metadata encrypted & error corrected
- [x] automatic expansion of ZDB storage containers when more storage needed
- [x] automatic monitoring when ZDB fails and recovery actions
- [ ] escalation to user when issue (telegram? or email?)
- [ ] helm charts & instructions to let QSFS to work in Kubernetes env's

## Deliverables

- documentation
- helm examples how to get started on any kubernetes cluster

# Remarks

- [x] storage can never be lost, not ever
- [x] reliability is always more important compared to availability (uptime)
- [x] reliability is always more important compared to performance
- [x] security is all done at QSFS level, on cloud level its 100% zero knowledge proof system

# Features which can be delivered later

- [x] basic reporting to statistics server like Grafana - > prometheus endpoint

**Comment by despiegk** [comment]
there seems to be a duplicate story, lets remove and focus on this one,
add info from other to this one

**Comment by LeeSmet** [comment]
Questions: 

> automatic payment from eVDC controller for resources used

I am currently working under the assumption that the binary will have a stellar wallet and grid identity, from which it can manage reservations on the grid all by itself. This would make this point obsolete?

> escalation to user when issue (telegram? or email?)

Considering we also want statistics exported in grafana, it might be better to just rely on grafana alerting to allow users to set up custom notifications exactly how they want it?

**Comment by xmonader** [comment]
> automatic payment from eVDC controller for resources used

this is obsolete indeed. I thought Kristof edited it, but didn't happen.

> Considering we also want statistics exported in grafana, it might be better to just rely on grafana alerting to allow users to set up custom notifications exactly how they want it?

I'm actually not sure, would that mean every user will have their own grafana instance? who will deploy these? but Indeed using grafana alerts could be the way to go

**Comment by LeeSmet** [comment]
I do imagine that everyone who deploys a qsfs instance is responsible for setting up a grafana instance. Not everyone will do this, as some people will not be interested in this. But I imagine that people who care about alerts in the first place would also care about monitoring and graphs to see how the system is doing, and so they would care enough to set up grafana alerst themselves. I also feel that grafana alerts could be way more customizable to the end user's liking, provided enough metrics are provided by zstor

**Comment by LeeSmet** [comment]
>  helm charts & instructions to let QSFS to work in Kubernetes env's

This is not achievable imo. QSFS is a storage privder, so it would require writing a custom CSI for it, or plainly running it in a pod and using a reverse local_path_provisioner storage class to map it to the host, then running another local_path_provisioner claim to expose it in another pod (not sure if this possible). Both solutions seem rather complex and non trivial to execute. Also, although kubernetes has support for ipv6 in its latest release inside pods, getting that to work requires manual setup of an ipv6 compliant CNI (which flannel currently isn't), so it seems that for now this will create quite some hassle (need to setup proxies for the 0-dbs). It's not feasible for this milestone, and given the above, I feel we should consider which direction to take first before continuing that.

> escalation to user when issue (telegram? or email?)

Such a service is also not tirivial to set up. For instance, telegram requires user interaction to set up. And emails without a dedicated email server will generally be blocked and flagged as spamm. As per the discussion above, I would first explore the option of letting this be handled by a grafana dashboard.

cc @despiegk

**Comment by LeeSmet** [comment]
Current status: 
Automatic expansion of storage, and replacement of failed storage is in progress (this goes hand in hand with some basic monitoring). The main troubles are that "good general purpose capacity planning" is tricky to do, based on the small amount of info that is available.

Aside from that, still need to implement metrics for prometheus, as well as the automatic repair if a backend goes down.

**Comment by LeeSmet** [comment]
Implementation for the provided requirements is done (bar the k8s/escalation point, for the reasons outlined previously). The only other thing not there is the 0-db protection, but that is a zos issue and does not block zstor/qsfs. Without a doubt there are lots of things which can (probably) be improved. However the current implementation is ready for testing and checks all required boxes.
