### ISSUE TITLE
TFGrid 2.x Farming/Minting needs follow 3.0 farming logic (June 15)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1055]
based on https://secure.threefold.tech/code/#/2/code/edit/B+gwgS24mPzAIMGMDqmlDjs-/
- [x] explorer pricing #1041 
- [x] farming 2.8 https://github.com/threefoldtech/home/issues/1042
- [x] minting to happen on all networks https://github.com/threefoldtech/tfexplorer/issues/315
- [x] show/filter farms/nodes that are compliant with grid 3 farming rules https://github.com/threefoldtech/tfexplorer/issues/314
- [x] explorer: new farmers need to be on 3.0 minting  https://github.com/threefoldtech/tfexplorer/issues/313
- [x] js-sdk farmmgmt: upgrade to 3.0 logic https://github.com/threefoldtech/js-sdk/issues/3096

**Comment by sasha-astiadi** [comment]
motivating user: not a technical issue, removed.

**Comment by sasha-astiadi** [comment]
question to be answered on minting @LeeSmet : why do we mint on devnet?
