### ISSUE TITLE
 ZOS uses Reliable MBus with Primitives 3: June 15 (phase 1)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1061]
## why

- will be used to deploy digital twins

## todo

- [x] finish models in vgrid/zosreq in line with https://staging.threefold.io/info/internet4#/internet4__tfgrid_primitives
- ~[ ] create example scripts which use these models to create workloads for common use cases  will be implemented in github.com/threefoldtech/zos3_v_examples~
- [x] kristof to review
- [x] implement primitives ZMACHINE & ZDB & PLANETARY_NETWORK support
    - [x] deploy ZMACHINE with ubuntu 21.04 connected to planetary network
    - [x] deploy ZDB and connect to it
    - [x] deploy container with flist
- [x] get feedback from deployment (ability to query status of a deployment)

## implementation

- models & code = vlang SDK in threefoldtech/vgrid.git
- allow ssh key to go in VM
- machines can go to internet over NAT

## remarks

- we don't focus on billing at all
- no network management yet (we need network manager for that), all just connected to planetary network for now

**Comment by muhamadazmy** [comment]
@despiegk we need to discuss `implement in ZOS using RMB` if that means that the node will actually POLL on the bus waiting for messages ? or some external client to the BUS will do that and then use the node REST API to do actions?

**Comment by sasha-astiadi** [comment]
will split it into 2 stories (mbus , primitives) and tag it here, as well as on 3.0 project

**Comment by sasha-astiadi** [comment]
user stories;
 story 1; Prepare Primitives 3 for MBus operations threefoldtech/zos#1297 
 https://github.com/threefoldtech/zos/issues/1298
story 2: ZOS integration with rmb (reliable message bus) threefoldtech/zos#1298 https://github.com/threefoldtech/zos/issues/1297

**Comment by sasha-astiadi** [comment]
team need to suggest a new realistic deadline

**Comment by sasha-astiadi** [comment]
need reestimation

**Comment by muhamadazmy** [comment]
Story is paused since we need to work on grid 2.9

**Comment by sasha-astiadi** [comment]
work continues as we go back to focusing on 3.0 again
