### ISSUE TITLE
Publishing tools 1.1 (June 8)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1063]
- [x] use config management through a singleton (one obj used everywhere, maxux knows) https://github.com/crystaluniverse/publishtools/issues/97
- [x] remove the unsafe constructs https://github.com/crystaluniverse/publishtools/issues/96
- [x] automatic def replacement doesn't work on longest match?  https://github.com/crystaluniverse/publishtools/issues/95
- [x] do same singleton for gittools https://github.com/crystaluniverse/publishtools/issues/100

**Comment by xmonader** [comment]
project in the repo is 2.7 
![image](https://user-images.githubusercontent.com/64129/120302304-1073ad00-c2ce-11eb-88a1-f0ddedfe9791.png)

is it 1.1 or 2.7?

**Comment by Hamdy** [comment]
Done

**Comment by despiegk** [comment]
once done build for OSX intel, ask kristof to do for arm OSX

**Comment by Hamdy** [comment]
@despiegk already done. we have binaries for linux and max_osx already please rebuild for mac arm
