### ISSUE TITLE
VDC speedup and recovery

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1068]
minimal improvements required

## deployment speedup
- [x] use max fee when deploying
- [x] creation of wallets 
- [x] creation of pools
- [x] vdc 3bot controller redeployment service https://github.com/threefoldtech/js-sdk/issues/3099
- [x] vdc load info improvements  https://github.com/threefoldtech/js-sdk/issues/3108
- [x] improve the speed of the deployment
  - [x] improving the 3bot deployment https://github.com/threefoldtech/js-sdk/issues/3137 
  - [x] move final payments to be as deployer service
- [x] improve pools creation/extension in the explorer side https://github.com/threefoldtech/tfexplorer/issues/323
- [x] enable pre-fetching of certs from ca server (ca1.grid.tf)

## master recovery
- [x]  https://github.com/threefoldtech/js-sdk/issues/3126
  - [x] https://github.com/threefoldtech/tfexplorer/issues/318

**Comment by OmarElawady** [comment]
The deployment are now down to ~ 8 minutes from 10. Going to take measurements of significant steps to pin the bottlenecks that needs improvements.

**Comment by OmarElawady** [comment]
Updates:
1. Deploy the worker in parallel with the 3bot and traefik upgrade.
2. Remove one unnecessary pool extension when deploying workers.

The time taken after payment until a usable vdc is 6:15 minutes broken down into these steps:

1. Creating pools: 66
2. Deploy external etcd: 36
3. master deployment: 80
4. wait cluster ready: 33
5. threebot: 52   (the time taken for the node to process the workload not the container initialization)
6. prepaid to provision transfer: 15
7. init fees: 16
8. funding diff: 33
9. renew_plan: 39

There exists some fluctuations in the steps time so it's not an exact measurement. The zdbs, workers, and traefik upgrade are done in prallel along with the threebot container. The master takes time to have ssh access and kube config after the node reports that the k8s workload was processed and before that kubectl is not available. And the cluster takes some additional time to be ready (running helm or kubectl on it fails with :6443 connection refused).

Total time taken for each step:
```
TIMESTAMP: start_deployment 2021-06-03 18:39:28.131791
TIMESTAMP: start_farms_selection 2021-06-03 18:39:29.702393
TIMESTAMP: end_farms_selection 2021-06-03 18:39:30.301781
TIMESTAMP: start_wallet_init 2021-06-03 18:39:46.172267
TIMESTAMP: end_wallet_init 2021-06-03 18:40:00.447771
TIMESTAMP: start_domain_check 2021-06-03 18:40:00.447944
TIMESTAMP: end_domain_check 2021-06-03 18:40:00.683094
TIMESTAMP: start_payment 2021-06-03 18:40:00.683279
TIMESTAMP: end_payment 2021-06-03 18:40:21.879294
TIMESTAMP: start_vdc 2021-06-03 18:40:21.882552
TIMESTAMP: start_vdc_pools 2021-06-03 18:40:21.885230
TIMESTAMP: end_vdc_pools 2021-06-03 18:41:27.288815
TIMESTAMP: start_vdc_network 2021-06-03 18:41:27.289031
TIMESTAMP: end_vdc_network 2021-06-03 18:41:33.021642
TIMESTAMP: start_one_zdb_batch 2021-06-03 18:41:33.471572
TIMESTAMP: start_one_zdb_batch 2021-06-03 18:41:33.750863
TIMESTAMP: start_etcd 2021-06-03 18:41:33.941576
TIMESTAMP: end_one_zdb_batch 2021-06-03 18:41:45.409323
TIMESTAMP: end_one_zdb_batch 2021-06-03 18:41:45.446675
TIMESTAMP: end_etcd 2021-06-03 18:42:09.585514
TIMESTAMP: start_master 2021-06-03 18:42:10.377896
TIMESTAMP: end_master 2021-06-03 18:43:29.496488
TIMESTAMP: start_workers 2021-06-03 18:43:29.894223
TIMESTAMP: start_master_ssh 2021-06-03 18:43:30.258156
TIMESTAMP: end_master_ssh 2021-06-03 18:44:03.307949
TIMESTAMP: start_threebot 2021-06-03 18:44:03.317938
TIMESTAMP: start_traefik_upgrade 2021-06-03 18:44:04.443455
TIMESTAMP: end_workers 2021-06-03 18:44:30.169618
TIMESTAMP: end_threebot 2021-06-03 18:44:55.544340
TIMESTAMP: end_vdc 2021-06-03 18:44:55.990112
TIMESTAMP: start_provision_transfer 2021-06-03 18:44:55.990324
TIMESTAMP: end_provision_transfer 2021-06-03 18:45:08.155380
TIMESTAMP: start_pay_init_fees 2021-06-03 18:45:08.155530
TIMESTAMP: end_pay_init_fees 2021-06-03 18:45:24.297380
TIMESTAMP: start_funding_diff 2021-06-03 18:45:24.299328
TIMESTAMP: end_traefik_upgrade 2021-06-03 18:45:46.626930
TIMESTAMP: end_funding_diff 2021-06-03 18:45:57.307256
TIMESTAMP: start_renew_plan 2021-06-03 18:45:57.307507
TIMESTAMP: end_renew_plan 2021-06-03 18:46:36.591900
TIMESTAMP: end_deployment 2021-06-03 18:46:37.181011
```

**Comment by MElborolossy** [comment]
Today We try to deploy a VDC without the last 3 steps `init fees, funding diff, and renew_plan`, the time seems not affected because the server still not ready and try to generate the certificate, this takes about 80 sec
Here is a detailed timeline:
```
TIMESTAMP: start_deployment 2021-06-06 13:40:44.535483
TIMESTAMP: start_farms_selection 2021-06-06 13:40:46.409173
TIMESTAMP: end_farms_selection 2021-06-06 13:40:47.101404
TIMESTAMP: start_wallet_init 2021-06-06 13:40:58.262718
TIMESTAMP: end_wallet_init 2021-06-06 13:41:07.132719
TIMESTAMP: start_domain_check 2021-06-06 13:41:07.132867
TIMESTAMP: end_domain_check 2021-06-06 13:41:07.154587
TIMESTAMP: start_payment 2021-06-06 13:41:07.154786
TIMESTAMP: end_payment 2021-06-06 13:41:59.214136
TIMESTAMP: start_vdc 2021-06-06 13:41:59.233574
TIMESTAMP: start_vdc_pools 2021-06-06 13:41:59.236609
TIMESTAMP: end_vdc_pools 2021-06-06 13:43:30.531984
TIMESTAMP: start_vdc_network 2021-06-06 13:43:30.532207
TIMESTAMP: end_vdc_network 2021-06-06 13:43:37.547778
TIMESTAMP: start_one_zdb_batch 2021-06-06 13:43:37.863669
TIMESTAMP: start_one_zdb_batch 2021-06-06 13:43:38.194493
TIMESTAMP: start_one_zdb_batch 2021-06-06 13:43:38.651375
TIMESTAMP: start_etcd 2021-06-06 13:43:38.729435
TIMESTAMP: end_one_zdb_batch 2021-06-06 13:44:00.270851
TIMESTAMP: end_one_zdb_batch 2021-06-06 13:44:04.555385
TIMESTAMP: end_one_zdb_batch 2021-06-06 13:44:06.635282
TIMESTAMP: end_etcd 2021-06-06 13:44:32.981210
TIMESTAMP: start_master 2021-06-06 13:44:33.889502
TIMESTAMP: end_master 2021-06-06 13:45:26.708545
TIMESTAMP: start_workers 2021-06-06 13:45:27.022981
TIMESTAMP: start_master_ssh 2021-06-06 13:45:27.466260
TIMESTAMP: end_master_ssh 2021-06-06 13:46:00.906577
TIMESTAMP: start_threebot 2021-06-06 13:46:00.930193
TIMESTAMP: start_traefik_upgrade 2021-06-06 13:46:02.657082
TIMESTAMP: end_workers 2021-06-06 13:46:19.130034
TIMESTAMP: end_threebot 2021-06-06 13:47:18.193246
TIMESTAMP: end_vdc 2021-06-06 13:47:18.626092
<- Here is the time that threebot server become ready with generated certificate ->
TIMESTAMP: end_deployment 2021-06-06 13:48:40.564185
```
