### ISSUE TITLE
QSFS additional stability improvements

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#1101]
- [x] Improve the handling of metadata backends: https://github.com/threefoldtech/0-stor_v2/issues/57
- [x] Expand the provided metrics: https://github.com/threefoldtech/0-stor_v2/issues/58
- [ ] Proper large scale testing: https://github.com/threefoldtech/quantum-storage/issues/7
- [ ] https://github.com/threefoldtech/0-stor_v2/issues/92

**Comment by LeeSmet** [comment]
Local testing shows zstor is working as expected. Need to scale up testing now, preferably by having a large scale , high throughput automated test setup. Also we need to test the grid interactions

**Comment by mhost39** [comment]
https://github.com/threefoldtech/0-stor_v2/issues/77
