### ISSUE TITLE
TF Jukebox V1.1

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/home#1106]
## Background

Since Blockchain deployments via jukebox using different approach than using k8s cluster on vdc, we need a separate image of each blockchain type, with different requirements and acceptance criteria
we will start for blockchains that supports ipv6 first
## Requirements
1- docs showing the full/complete steps to deploy that blockchain on a container
2- all required env vars with descriptions 
3- a working image 
4- mention if this blockchain supports ipv6 or not in the docs
5- required (cpu,memory and disksize)  for each image
6- path of the entry_point
## Acceptance Criteria

- [ ] no kubectl exec command on front end or anything related specific to kubernetes
- [ ] no manual interference during the deployments, deployment steps should be in a fully automated way we collect all required info in a chatflow and deploy after that without manual actions on the machine
- [ ] complete docs
- [ ] flist with the image "tested on our grid" 
## Blockchains that we should support
- Parity
- [ ] [Create jukebox image for parity ](https://github.com/threefoldtech/tf-images/issues/43)
- [ ] [Create Chatflow for parity](https://github.com/threefoldtech/tf_jukebox/issues/72)
- Tomochain
- [ ] [Create  jukebox image for tomochain ](https://github.com/threefoldtech/home/issues/1126l)
- [ ] [Create Chatflow for tomochain ](https://github.com/threefoldtech/tf_jukebox/issues/73)

**Comment by sasha-astiadi** [comment]
@ashraffouda casperlabs dont support ipv6, suggest tomochain next @abdulgig

**Comment by sasha-astiadi** [comment]
updated issue to include tomochain instead of casper. @ashraffouda
