### ISSUE TITLE
MVP Blockchain secured secure browsing

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1111]
## What is blockchain secured browsing

This uses the secure browsing solution that is being developed/contracted by TF tech (Juimber).  What is added to make this blockchain secured are elements from the Digibyte technology stack.
- blockchain secured access.  DiGi-Id is a digibyte asset that provides secure access and uses the DGB blockchain for it.  There an integration issue open to integrating it to TF Technology (https://github.com/threefoldtech/js-sdk/issues/2788)
- blockchain secured logging and fingerprinting.

It's this wrapper around the TF product that makes it blockchain secured.

Specific specifications that are considered to be important for the secure browsing MVP

### Access
- [ ] Digi-ID integration to provide password-less access to the service
- [ ] secure browsing "engines" need to be restricted to a specific group of users. The use case is for Enterprises and there might be 2 deployment methods:  privately-owned capacity and public capacity.
- [ ] easy management if adding and removing people from secure browsing groups.

### Operations
- [ ] provisioning a secure browsing engine should be something a medium technical person can do. Based on requirements (size number of max users (pre-productize, 5, 10, 100?), location, logging options (minimal, medium, maximum))
- [ ] individual / group access management 
- [ ] 24x7 open or business hours only
- [ ] access by secure https traffic from anywhere or certain locations

### Functionality
- [ ] functionality as currently in the secure browser (https://browser.staging.jimber.org/#https://www.google.com/)
- [ ] multiple browser support (maybe not MVP, but roadmap item).
- [ ] no added step to use the secure browsing engine
- [ ] 100% compatible with the normal browser experience

### Reporting / Logging
- [ ] logging options for datapoint of secure browsing users.  configurable logging options as this needs to be inline with the country and company governance requirements.
- [ ] reporting / log explorer on the DGB blockchain (simple, medium, maximum).
     - [ ] user identity (unique, maybe anonymised
     - [ ] user start / end time/date of browsing session
     - [ ] user URLS / services used
- [ ] customizable explorer reporting

## TODO 
- get the specifications as they are being considered for Kutana and use them for this product
- add the specifications for blockchain secured access
- add the specifications for blockchain secured logging 
-
