### ISSUE TITLE
Rest api for gridproxy

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1163]
- graphql goes to non public
- nicely documented REST api
- KIS

## TODO

https://github.com/threefoldtech/tfgridclient_proxy/projects/7
- [x] specs in text format https://github.com/threefoldtech/tfgridclient_proxy/issues/92
- [ ] kristof +++ review text
- [x] specs in openapi https://gridproxy.dev.grid.tf/swagger/index.html
- [x] community review openapi (forum) https://forum.threefold.io/t/community-review-for-grid-proxy-api/2313
- [ ] kristof +++ review openapi https://gridproxy.dev.grid.tf/swagger/index.html
- [x] implement as only interface to TFChain & RMB
- [x] build scripts in docker for the separate components

note: implemenntation on both gridproxy repo n zos repo (to be linked later)

**Comment by muhamadazmy** [comment]
Repository: 
https://github.com/threefoldtech/tfgridclient_proxy


API Specs:
https://github.com/threefoldtech/tfgridclient_proxy/blob/development/docs/swagger.yaml

**Comment by xmonader** [comment]
everything related to deployments and docs of validators moved here https://github.com/threefoldtech/home/issues/1184 (out of the scope of this story)

**Comment by xmonader** [comment]
@despiegk please make some time to check
