### ISSUE TITLE
Improve zos VM user experience

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#1190]
# Description

Currently the user experience for using a VM on the grid is pretty lacking. There is a lot of knowledge needed which can only be gained by browsing to the zos code, and the structure in place does not conform to any industry standard. By changing the current approach to use cloud init, we would remove multiple limitations we currently have, and also be compatible with industry standards. This would greatly simplify the process of creating VM images, as well as provide a better experience for users of such images.

## Tasks

- [ ] [Expect an actual disk image rather than a btrfs filesystem](https://github.com/threefoldtech/zos/issues/1622)
- [ ] [Support cloud init](https://github.com/threefoldtech/zos/issues/1624)
- [ ] [Make providing a kernel for the VM optional](https://github.com/threefoldtech/zos/issues/1623)
- [ ] [Make sure there is documentation about creating VM images](https://github.com/threefoldtech/zos/issues/1625)
