### ISSUE TITLE
v3 documentation and manual Doc Preparation for 3.A-5

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1193]
- [x] [containers or vm's in zos](https://github.com/threefoldtech/home/issues/1183)
- [ ] [farm management feature on tfconnect app](https://github.com/threefoldfoundation/info_manual3/issues/49)
- [x] how to deploy[ Mattermost, Discourse (forum), Presearch Node and Casperlabs validator node.](https://github.com/threefoldtech/home/issues/1153)
- [x] [tfchain how to apply to be a validator and council member] (https://github.com/threefoldtech/home/issues/1154) docs here https://github.com/threefoldtech/tfchain/blob/development/substrate-node/doc/creating_validator.md
- [x] [how to buy tft using fiat ](https://github.com/threefoldfoundation/info_manual3/issues/48)
- [ ] [dedicated nodes](https://github.com/threefoldfoundation/info_manual3/issues/50)
- [x] ssh documentation

**Comment by renauter** [comment]
SSH documentation created for the manual:

https://github.com/threefoldfoundation/info_manual3/pull/47
