### ISSUE TITLE
erc20 improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#120]
- [x] [ability to query the status of the ethereum sync in tfchaind/tfchainc](https://github.com/threefoldfoundation/tfchain/issues/303)
- [x] [erc20 bridgec client](https://github.com/threefoldfoundation/tfchain/issues/304)
- [x] [Bridge and tfchaind use same port for ethereum node](https://github.com/threefoldfoundation/tfchain/issues/317)
