### ISSUE TITLE
Testplan alpha6

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1237]
#### Testplan for v 3.0.0 Alpha-6 should cover:
- development project: https://github.com/threefoldtech/home/projects/8
- Expected release plan: https://forum.threefold.io/t/threefold-product-updates-tfgrid-v3-a-6-plan-may-2022/2808
- Testlodge Run: https://app.testlodge.com/a/26076/projects/40893/runs/640708
- Known Issues: https://github.com/threefoldtech/home/issues/1249#issuecomment-1143429168

### Schedule
- Alpha-6 expected to be on testnet 14 May 2022 (@xmonader will confirm with a comment on this story that its ready on testnet)
- All tets and verifications should be within one week maximum.

#### Quick verification:
- [x] https://github.com/threefoldtech/home/issues/1177 (Note by Ken: Live in production, can check wallet in TF Connect app)
- [ ] https://github.com/threefoldtech/home/issues/1226
- [x] https://github.com/threefoldtech/home/issues/1186 (Note by Ken: Story was closed due to duplicate on Alpha 7 which will be followed up there, so nothing to verify here)
- [x] https://github.com/threefoldtech/home/issues/1146 (Note by Ken: No need to verify, fully replaced with v1.2 already)
- [x] https://github.com/threefoldtech/home/issues/1225
- [x] https://github.com/threefoldtech/home/issues/1197
- [x] https://github.com/threefoldtech/home/issues/1195

#### Validation and Add new testcases to testlodge:
- [x] https://github.com/threefoldtech/home/issues/1192 (Note by ken: Fully live on production already, so can just check the wallet inside ThreeFold Connect)
Testsuite (https://app.testlodge.com/a/26076/projects/40893/suites/204782)
- [ ] https://github.com/threefoldtech/home/issues/1149
Need to add testcases to cover this
- [ ] https://github.com/threefoldtech/home/issues/1222
add tests to cover new changes in Testsuite (https://app.testlodge.com/a/26076/projects/40893/suites/194376)
- [x] https://github.com/threefoldtech/home/issues/1227
Testsuite (https://app.testlodge.com/a/26076/projects/40893/suites/193825)
- [x] grid_weblets 1.4.1 https://github.com/threefoldtech/grid_weblets/projects/14
Testsuite (https://app.testlodge.com/a/26076/projects/40893/suites/195824)
- [ ] grid_weblets 1.4.3 https://github.com/threefoldtech/grid_weblets/projects/16

**Comment by ramezsaeed** [comment]
![Uploading Screenshot from 2022-06-12 14-06-46.png…]()

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/home/issues/1149

https://github.com/threefoldtech/node-pilot-light

@maxux Is this deployed on testnet already? the QA needs to test the first version

**Comment by sasha-astiadi** [comment]
remove following issues from the list:

- 
-
add issues listed in 'done' column to this issue

**Comment by ramezsaeed** [comment]
![Screenshot from 2022-06-15 11-33-30](https://user-images.githubusercontent.com/16083592/173795419-02224107-6d94-4b25-b7fc-9a37d4b4495f.png)
