### ISSUE TITLE
A-6 Blocking issues

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1250]
- Blocking Issues (make known issues, make sure is on release notes)
  - [x] Weblets 1.4.2 https://github.com/threefoldtech/grid_weblets/projects/14
  - [x] Weblets 1.4.3 https://github.com/threefoldtech/grid_weblets/projects/16
  - [x] Terraform not reliable enough in relation to timeouts (see MMW) (thabet)
  - [x] [We can’t just delete workloads](https://github.com/threefoldtech/zos/issues/1709) -> pause/resume  (azmy/dylan)
  - [x] Planetary Network: we choose 4 good ygg nodes, document/use them everywhere (operations)
         [ peer list](https://github.com/threefoldtech/tf_operations/issues/852#issuecomment-1118547995)
         https://github.com/threefoldtech/planetary_network/issues/20
  - [x] [failed to open /dev/kvm](https://github.com/threefoldtech/test_feedback/issues/187#issuecomment-1140428909) 
  - [x] [Bridge isn't functional](https://github.com/threefoldtech/tfchain_tft_bridge/issues/75) 
  - [x] [Run automation test against testnet and mainnet](https://github.com/threefoldtech/grid3_client_ts/issues/279)
- Known issues
  - [x] QSFS not enough tested yet, testplan?

**Comment by sasha-astiadi** [comment]
@xmonader post by kds https://forum.threefold.io/t/can-a-farmer-manipulate-the-farming-rules/1175

**Comment by sasha-astiadi** [comment]
- [ ] Community member showed how farming can be faked (solution being created in 2 parts: (1) [capacity certifier](https://www.google.com/url?q=https://github.com/threefoldtech/home/issues/1245&sa=D&source=docs&ust=1654296175885316&usg=AOvVaw2-ALVpfJLWsbOm6y_a54_h) this is for a7, and (2) how to avoid fake farming? TBD ) 

moved to a7

**Comment by sasha-astiadi** [comment]
- [ ] Minting details / Visibility of farming report on App + Portal (please add to documentation) - issue [here](https://www.google.com/url?q=https://github.com/threefoldtech/home/issues/1255&sa=D&source=docs&ust=1654295942042913&usg=AOvVaw3cAWkqIgjp3ded2O9U1zGD)

its a feature request for a7

**Comment by sasha-astiadi** [comment]
Unvesting (1 week + jimber work)
- [ ] https://github.com/threefoldtech/home/issues/1252

@robvanmieghem eta? a7 or a6 feature?

**Comment by sasha-astiadi** [comment]
@sabrinasadik please comment here,  the validator issue here so we will know if its for a6 or not.. just create a new issue (containing the question from community) and link it here...

**Comment by sasha-astiadi** [comment]
- [ ] Unvesting (1 week + jimber work)
          - [ ] https://github.com/threefoldtech/home/issues/1252
          
          moved to a7
