### ISSUE TITLE
STORY: tfchain validation improvements

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/home#1283]
- [x] Validation for Public Config (Node) https://github.com/threefoldtech/tfchain/issues/273
- [x] Validation for Interfaces (Node) https://github.com/threefoldtech/tfchain/issues/273
- [x] Validation for Public IPs (Farm) 
- [x] Validation for Twin IPs
- [x] Rework public IPs on Contract -> is now a list with the actual public IP object
- [x] Billing executed in a transactional https://github.com/threefoldtech/tfchain/issues/356
- [x] Restriction of deployment hash length (32 bytes)
- [x] Migration for contracts
- [x] Migration for nodes and farms
- [ ] Additional testing

**Comment by ramezsaeed** [comment]
@DylanVerstraete 
why is this Blocked ?

**Comment by mohamedamer453** [comment]
@ramezsaeed I moved this story to blocked a couple of days ago since the validation issues still had some problems but they're fixed now.

These were verified in https://github.com/threefoldtech/tfchain/issues/273 & https://github.com/threefoldtech/tfchain/issues/420

> * [x]  Validation for Public Config (Node) [Implement a maximum size on all types that are filled in by the user or ZOS tfchain#273](https://github.com/threefoldtech/tfchain/issues/273)
> * [x]  Validation for Interfaces (Node) [Implement a maximum size on all types that are filled in by the user or ZOS tfchain#273](https://github.com/threefoldtech/tfchain/issues/273)
> * [x]  Validation for Public IPs (Farm)
> * [x]  Rework public IPs on Contract -> is now a list with the actual public IP object

THis was verified in https://github.com/threefoldtech/tfchain/issues/343

> * [x]  Validation for Twin IPs

This was verified in https://github.com/threefoldtech/tfchain/issues/356

> * [x]  Billing executed in a transactional [Execute billing in a transactional operation tfchain#356](https://github.com/threefoldtech/tfchain/issues/356)

This was verified in https://github.com/threefoldtech/tfchain/issues/393

> * [x]  Restriction of deployment hash length (32 bytes)

For the rest of the tasks i couldn't find the issues related to them.

> * [x]  Migration for contracts
> * [x]  Migration for nodes and farms
> * [ ]  Additional testing

**Comment by DylanVerstraete** [comment]
Rest is done, thanks!
