### ISSUE TITLE
tft-erc20 deployment

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#136]
- [ ] [Multiple light clients from the same external ip does not work](https://github.com/threefoldfoundation/tfchain/issues/281)
  - [x] [Create an flist for an ethereum full node](https://github.com/threefoldfoundation/tfchain/issues/292)
    - [x] package a startup script
    - [x]  publish it to tf_official apps
  - [x] deploy full node for testnet
    - [x] deployment of ethereum full node fails to run
    - [x] convert cli status command on testnode to JSON RPC
  - [ ] [Enable ethvalidation on the testnet nodes that create blocks](https://github.com/threefoldfoundation/tfchain/issues/323)
    - [x] [Can't set custom eth bootnodes in tfchain templates]
(https://github.com/threefoldfoundation/tfchain-templates/issues/4)
    - [ ] [Zrobot only checks out master repo for templates when booting]
(https://github.com/threefoldtech/0-robot/issues/66)
    - [x] [Can't get proper bootnode url from geth](https://github.com/threefoldfoundation/tfchain-templates/issues/6)
- [x] [blockcreator with ethvalidation and unencrypted wallet is not creating blocks](https://github.com/threefoldfoundation/tfchain/issues/309)
- [x] [Initially adding the supplied bootnodes once seems not good enough](https://github.com/threefoldfoundation/tfchain/issues/318)
- [x] [Block creator template can't be started](https://github.com/threefoldfoundation/tfchain-templates/issues/11)
- [ ] [bridge flist](https://github.com/threefoldfoundation/tfchain/issues/337)
- [ ] [unencrypted wallet blocks daemon startup](https://github.com/threefoldtech/rivine/issues/522)
- [ ] [Tfchain template issue](https://github.com/threefoldfoundation/tfchain-templates/issues/13)

**Comment by LeeSmet** [comment]
deplying a geth instance led to the following error:

```
In [25]: geth = robot.services.create(GETH_ID, 'testnet_geth', data)
---------------------------------------------------------------------------
LoopExit                                  Traceback (most recent call last)
/usr/local/bin/js_shell in <module>()
----> 1 geth = robot.services.create(GETH_ID, 'testnet_geth', data)

/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/ZeroRobotManager.py in create(self, template_uid, service_name, data, public)
    171             raise ServiceCreateError(e['message'], err)
    172 
--> 173         return self._instantiate(new_service)
    174 
    175     def find_or_create(self, template_uid, service_name, data, public=False):

/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/ZeroRobotManager.py in _instantiate(self, data)
     48     def _instantiate(self, data):
     49         if hasattr(data, 'secret') and data.secret:
---> 50             self._client = config_mgr.append_secret(self._client.instance, data.secret)
     51             # force re-creation of the connection with new secret added in the Authorization header
     52             self._client._api = None

/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py in append_secret(self, instance, secret)
    114 
    115     def append_secret(self, instance, secret):
--> 116         return self._send_cmd(self._append_secret, [instance, secret])
    117 
    118     def remove_secret(self, instance, service_guid):

/opt/code/github/threefoldtech/0-robot/zerorobot/dsl/config_mgr.py in _send_cmd(self, func, args)
     36         resp_q = Queue(maxsize=1)
     37         self._queue.put((func, args, resp_q))
---> 38         resp = resp_q.get()
     39         if isinstance(resp, Exception):
     40             raise resp

/usr/local/lib/python3.5/dist-packages/gevent/_queue.cpython-35m-x86_64-linux-gnu.so in gevent._queue.Queue.get()

/usr/local/lib/python3.5/dist-packages/gevent/_queue.cpython-35m-x86_64-linux-gnu.so in gevent._queue.Queue.get()

/usr/local/lib/python3.5/dist-packages/gevent/_queue.cpython-35m-x86_64-linux-gnu.so in gevent._queue.Queue.__get_or_peek()

/usr/local/lib/python3.5/dist-packages/gevent/__waiter.cpython-35m-x86_64-linux-gnu.so in gevent.__waiter.Waiter.get()

/usr/local/lib/python3.5/dist-packages/gevent/__greenlet_primitives.cpython-35m-x86_64-linux-gnu.so in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch()

/usr/local/lib/python3.5/dist-packages/gevent/__greenlet_primitives.cpython-35m-x86_64-linux-gnu.so in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch()

/usr/local/lib/python3.5/dist-packages/gevent/__greenlet_primitives.cpython-35m-x86_64-linux-gnu.so in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch()

src/gevent/__greenlet_primitives.pxd in gevent.__greenlet_primitives._greenlet_switch()

LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7f2cfc12c978 epoll pending=0 ref=0 fileno=17 thread_ident=0x7f2d11f41700>
	Handles:
[]
```

which seems to have left the robot in an inconsistent state. The service is not listed, but trying to create a  new service with the same name fails because the name is supposedly already taken. At this point, the robot is not even starting because it does not have the templates for this service after a restart somehow.

**Comment by LeeSmet** [comment]
full node is now running for testnet

**Comment by LeeSmet** [comment]
While testing the new template version, the node lost internet access for no apparent reason. While trying to solve this the node was rebooted, but internet connectivity still did not work, so the node is failing to boot as a result now.

**Comment by LeeSmet** [comment]
geth deployed and now syncing

**Comment by LeeSmet** [comment]
Yesterday some bugs were discovered and fixed, however the geth node needs to sync again as the progress was lost due to one of these bugs

**Comment by LeeSmet** [comment]
Seems like the current way the ethbootnodes are added does not allow us to connect to the ethereum full node

**Comment by LeeSmet** [comment]
Seems to work on 
 a local node with https://github.com/threefoldfoundation/tfchain/commit/239f9e755eb31b9e4b04a332e0d36a2cb40e9c07

**Comment by LeeSmet** [comment]
Did some changes to the way the flists are build, now getting the following build errors:

```
# github.com/mholt/caddy/caddytls
/root/go/pkg/mod/github.com/mholt/caddy@v0.11.5/caddytls/setup.go:174:28: cannot use value (type "github.com/xenolf/lego/certcrypto".KeyType) as type "github.com/go-acme/lego/certcrypto".KeyType in assignment
/root/go/pkg/mod/github.com/mholt/caddy@v0.11.5/caddytls/setup.go:354:4: cannot use config.Manager.KeyType (type "github.com/go-acme/lego/certcrypto".KeyType) as type "github.com/xenolf/lego/certcrypto".KeyType in field value
```

**Comment by LeeSmet** [comment]
tfchain autobuilder is now working correctly again

**Comment by LeeSmet** [comment]
now blocked on https://github.com/threefoldfoundation/tfchain-templates/issues/11

**Comment by LeeSmet** [comment]
Block creator now running, connected to our geth through the zerotier address, and seems to be sycning 

```
In [67]: con.client.system('/bin/tfchainc erc20').get()
Out[67]: 
STATE: 0 SUCCESS
STDOUT:
Starting block height: 4587519
Current block height: 4613823
Highest block height: 5390531

STDERR:

DATA:
```

**Comment by LeeSmet** [comment]
validation daemon won't progress past block 193,605

**Comment by LeeSmet** [comment]
The problem occurs because in the past, we upgraded our contract implementation, and the new implementation the withdrawel event signature changed. As a result, the new bindings (which replaced the old ones) can no longer unpack the old withdrawal events, and by extension no longer validate them. This affects a couple of blocks likely. This was not caught before because while developing the new style contract is always used, and existing block creators already validated the old withdrawals, so when these go the new code they also only used it to validate new events.

There are a couple of solutions:

1. Ignore old style txes
2. Add the old contract bindings back, and implement some logic which delegates the unpacking to the right contract depending on the block height
3. Reset testnet to before the first erc20 txes (which likely already needs to happen due to the 3bot/digitalID refactoring)

**Comment by LeeSmet** [comment]
https://github.com/threefoldfoundation/tfchain/issues/336

**Comment by LeeSmet** [comment]
For some unknown reason, light clients (validators) don't connect to the geth node, but the bridge does

**Comment by hossnys** [comment]
Hello threefoldtech/homeThank you for contacting us. This is an automated response confirming the receipt of your ticket. Our team will get back to you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject so that we can track your replies.Ticket ID: AAAA-0000-0013  You can check the status of or update this ticket online at: http://localhost/check_ticket/eyJpdiI6ImdJbm9cL3lReWVpeko2dlRcL3kxOHlVUT09IiwidmFsdWUiOiI2UXZMQWR2MDBxUThnNlZmaTE1cEJRPT0iLCJtYWMiOiJjNGRlNTZkYjJhZmJmMzE1YTkwZTE0NDc0Njc3NjVkODUyY2IxMWI5ZWIzY2RjYzdiOTcwNTFjYWYzYTc1Yzk0In0=

**Comment by hossnys** [comment]
Hello threefoldtech/home, This email is confirmation that you are now registered at our helpdesk.Registered Email: reply@reply.github.comPassword: ZEJcoPURUoYou can visit the helpdesk to browse articles and contact us at any time: http://localhostThank You.Kind Regards, Support Center

**Comment by LeeSmet** [comment]
While running Tshark on the zt interface, packets are being captured which do indicate that the light clients attempt to connect to our geth node. This would indicate that geth refuses these connections for some reason

**Comment by LeeSmet** [comment]
Seems like every now and then there is a tcp connection being opened, which pushes data once and then gets closed again

**Comment by LeeSmet** [comment]
currently syncing local dockerized geth node, so the setup can be recreated locally to see if the problem can be reproduced
