### ISSUE TITLE
terraform for 3.8

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1360]
- [ ] update terraform code for 3.8
  - [ ] terraform update https://github.com/threefoldtech/terraform-provider-grid/issues/373
  - [ ] capacity reserver resource https://github.com/threefoldtech/terraform-provider-grid/issues/373
- [ ] resources docs upgrade https://github.com/threefoldtech/terraform-provider-grid/issues/375
- [ ] examples upgrade https://github.com/threefoldtech/terraform-provider-grid/issues/376
- [ ] update manual docs https://github.com/threefoldtech/terraform-provider-grid/issues/376
