### ISSUE TITLE
Rivine & tfchain improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#143]
- [ ] [Clean up if build.DEBUG ..panic everywhere](https://github.com/threefoldtech/rivine/issues/489)
- [x] [Integrate parseDescription in Rivine CLI Code](https://github.com/threefoldtech/rivine/issues/490)
- [x] [Add debug logging to the gateway module](https://github.com/threefoldtech/rivine/issues/488)
- [x] [Remove parsedescription logic for --data flags in cli](https://github.com/threefoldfoundation/tfchain/issues/325)
- [x] [Move the bootstrap-peers flag to Rivine](https://github.com/threefoldfoundation/tfchain/issues/327)
  - [x] [Add a bootstrap-peers flag to override the default bootstrap peers](https://github.com/threefoldtech/rivine/issues/502)
- [x] [Rivine: Create a minting extension](https://github.com/threefoldtech/rivine/issues/503) 
- [ ] [Host the explorer html ourselves](https://github.com/threefoldtech/rivine/issues/505)
- [x] [tfchain:move the 3bot transactions to a seperate file](https://github.com/threefoldfoundation/tfchain/issues/331)
- [x] [Why are there custom wallet http handlers?](https://github.com/threefoldfoundation/tfchain/issues/328) @glendc
- ~[ Rivine : Create a multisignature extension](https://github.com/threefoldtech/rivine/issues/506)~
- [ ] [Drop the Multisig registration from tfchain as it is no longer needed](https://github.com/threefoldfoundation/tfchain/issues/332)
- [x] [Daemon thinks it is always synced](https://github.com/threefoldtech/rivine/issues/515)
- [x] [Transactionpool logging](https://github.com/threefoldtech/rivine/issues/520)
- [ ] [Harden block creation tx detection against forks](https://github.com/threefoldtech/rivine/issues/523)

**Comment by sabrinasadik** [comment]
@robvanmieghem do you have time to review it or assign someone to do so pls
