### ISSUE TITLE
3.11 testplan

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1437]
#### Test plan for v 3.11.x should cover:
- development project: https://github.com/orgs/threefoldtech/projects/196
- Testlodge Run: 
- Known Issues: https://github.com/threefoldtech/home/issues/1438

### Schedule
- 3.11.x expected to be on QAnet July 1st
- All tests and verification should be within one week maximum.

#### Main Features:
- [GPU support](https://github.com/threefoldtech/home/issues/1392)
- [TFT on ethereum + bridge](https://github.com/threefoldtech/home/issues/1311)

#### Quick verification:
- [ ] [TFT on ethereum + bridge](https://github.com/threefoldtech/home/issues/1311)
- [ ] [Forum post and howto for TFT on Ethereum](https://github.com/threefoldtech/home/issues/1435)
- [ ] [BSC bridge multisig improvements](https://github.com/threefoldtech/home/issues/1424)

#### Validation and Add new testcases to testlodge:
- [ ] [[research] file upload support for rmb-peer](https://github.com/threefoldtech/rmb-rs/issues/132)
- [x] [GPU support](https://github.com/threefoldtech/home/issues/1392)
- [x] [Tfchain improvements Part 2#1433](https://github.com/threefoldtech/home/issues/1433)

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-08-31 10-33-45](https://github.com/threefoldtech/home/assets/16083592/90a92957-44b7-4691-a142-77c179eab24f)

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-08-31 10-35-14](https://github.com/threefoldtech/home/assets/16083592/a690572c-b3dd-429e-bd95-606557b0874b)
only GPU test cant run yet, waiting for nodes with GPU to be lunched in testnet

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-09-25 15-18-34](https://github.com/threefoldtech/home/assets/16083592/f2774ce2-936b-457e-b73b-8cee540db45c)
