### ISSUE TITLE
NaCl improvements

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#144]
- Improvements:
   - [ ] [store ED25519 Key instead of Curve 25519 Key](https://github.com/threefoldtech/jumpscaleX/issues/226)
   - [ ] [make the module completely non-interactive](https://github.com/threefoldtech/jumpscaleX/issues/230)

- Dont Agree to do now (kristof, lets discuss)
   - [ ] [remove optional `die` parameter](https://github.com/threefoldtech/jumpscaleX/issues/231)
   - [ ] [expand API in j.data.nacl](https://github.com/threefoldtech/jumpscaleX/issues/229), can wait
   - [ ] [make encryption of private key opt-in](https://github.com/threefoldtech/jumpscaleX/issues/227) we can be opinionated, lets discuss

- Questions:
   - [ ] [is private key storage required](https://github.com/threefoldtech/jumpscaleX/issues/228)?
   - [ ] [review NaCl module](https://github.com/threefoldtech/jumpscaleX/issues/174)

**Comment by zaibon** [comment]
Blocked on JSx multiple branch issue. Need to have a single development branch to be able to make progress on this.

**Comment by despiegk** [comment]
make encryption of private key opt-in CANNOT BE OPT IN

**Comment by zaibon** [comment]
While doing this work we should also take in account what has been decided in this issue: https://github.com/threefoldfoundation/3bot/issues/8

To make sure we have everything ready for the 3bot key management
