### ISSUE TITLE
New Applications in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1512]
- [ ] Images: https://github.com/threefoldtech/tf-images/issues/195 
	- [x] threefoldtech/tf-images#196
	- [x]  threefoldtech/tf-images#197
	- [x]  threefoldtech/tf-images#199
	- [x]  threefoldtech/tf-images#201
- [ ] Dashboard
  - [x] threefoldtech/tfgrid-sdk-ts#2010
  - [x] threefoldtech/tfgrid-sdk-ts#2011
  - [x] threefoldtech/tfgrid-sdk-ts#2012
  - [x] threefoldtech/tfgrid-sdk-ts#2013
  - [x] threefoldtech/tfgrid-sdk-ts#2014
  - [x] threefoldtech/tfgrid-sdk-ts#2015
