### ISSUE TITLE
0-OS research

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#153]
- [x] [IPC infrastructure architecture & design](https://github.com/threefoldtech/0-OS_research/issues/13)
- [x] [Inter node communication](https://github.com/threefoldtech/0-OS_research/issues/11)
- [ ] [Research and design for versioning, update and upgrades architecture & design](https://github.com/threefoldtech/0-OS_research/issues/10)
- [x] [Design pid 1 architecture & design](https://github.com/threefoldtech/0-OS_research/issues/9)
- [x] [Design flist module architecture & design](https://github.com/threefoldtech/0-OS_research/issues/8)
- [ ] [Design metric/monitoring module architecture & design](https://github.com/threefoldtech/0-OS_research/issues/7)
- [ ] [Design Virtual machine module architecture & design](https://github.com/threefoldtech/0-OS_research/issues/6)
- [x] [Design container module architecture & design](https://github.com/threefoldtech/0-OS_research/issues/5)
- [x] [Design storage module architecture & design](https://github.com/threefoldtech/0-OS_research/issues/4)
- [ ] [Research OCI runtime architecture & design](https://github.com/threefoldtech/0-OS_research/issues/3)
- [x] [Research/choose RPC framework architecture & design](https://github.com/threefoldtech/0-OS_research/issues/2)
- [ ] [Formalize the concept of DSL next to the public API architecture & design](https://github.com/threefoldtech/0-OS_research/issues/1)

**Comment by muhamadazmy** [comment]
Progress has been checked above

**Comment by muhamadazmy** [comment]
We still discussing networking, it's one of the complex points that we need to figure atm for a large scale network

**Comment by muhamadazmy** [comment]
Did more reading about advanced networking this includes VRF and BGP

**Comment by muhamadazmy** [comment]
More discussions  about networking, we also need to create a task to spec the DSL.

**Comment by muhamadazmy** [comment]
Write down initial version of DSL

**Comment by muhamadazmy** [comment]
no updates since more higher prio issues came along

**Comment by muhamadazmy** [comment]
no progress on dsl yet

**Comment by muhamadazmy** [comment]
Working on a POC for PID that uses rust+tokio will create a repo once i have the basic structure of the implementation.
