### ISSUE TITLE
3.14 Testplan

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1533]
### Test plan for v 3.14.x release on TFgrid
- development project: https://github.com/orgs/threefoldtech/projects/206
- Known Issues: https://github.com/threefoldtech/home/issues/1532

### Schedule
- 3.14.x is devided into two Releses
    - 2.4.x expected to be on QAnet on: April 8/2024 (released on 22/5/2024)
    - 2.5.x expected to be on QAnet on: June 9/2024 (released on 11/6/2024)
- All tests and verification should be done on QAnet within one week maximum.
- After deploying on Testnet will keep it for one week before go to Mainnet in order to get tested by the community.

### Test the main features in 3.14.x release:
- Multiple SSH Keys
- More application images
- ThreeFold connect app new update 3.9.1
- farmerbot updates
- pulumi support mycelium

## Test Reports
- Testlodge Run: 
     - QAnet:
         - [QAnet 3.14 TestRun 2.4_rc1](https://app.testlodge.com/a/26076/projects/40893/runs/740458)
         - [QAnet 3.14 TestRun 2.4_rc2](https://app.testlodge.com/a/26076/projects/40893/runs/741479)
         - [Qanet testrun V2.5](https://app.testlodge.com/a/26076/projects/40893/runs/746337)
     - Testnet:
         - [Testnet 3.14 TestRun 2.4.0](https://app.testlodge.com/a/26076/projects/40893/runs/741479)
     - Mainnet:
         - [Mainnet TestRun 2.4.2](https://app.testlodge.com/a/26076/projects/40893/runs/743617)
         - [Atef Dashboard 2.4.2](https://app.testlodge.com/a/26076/projects/40893/runs/743616)

## Roles and Responsibilities
1. verification are done on Devnet (team members verify/ Ramez can close)
2. release on QAnet done by dev team approval.
3. QA team starts new test run iteration on Qanet.
4. BAM(Bug Assessment Meeting) is needed to approve the release and address the reported issues.
5. once approved the release go to Testnet.
6. QA team starts new test run iteration on Testnet.
7. BAM is needed to approve the release and address the reported issues.
8. once approved release kept on Testnet for two weeks before go to Mainnet.
9. once release on Mainnet QA team starts new test run iteration on Mainnet.
#### This test plan is maintained by QA team:
@ramezsaeed 
@khaledyoussef24 
@A-Harby 

## Main Features Testing and Validation:
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1882
    - Related issues: 
        - [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2543
        - [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2372
    - Testsuite: https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#suite_section_430164
- [ ] https://github.com/threefoldtech/tf-images/issues/195
    - Related issues: 
        - [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2504
    - Testsuiite: TODO
- [x] Threefold connect new app version 3.9.1
    - Related issues: 
        - [x] https://github.com/threefoldtech/threefold_connect/issues/602
    - Testsuiite: https://app.testlodge.com/a/26076/projects/40893/suites/206114
- [x] farmerbot
    - Related issues: 
        - [x] improved capacity planning to wakeup nodes https://github.com/threefoldtech/tfgrid-sdk-go/issues/978
        - [x] allowing farmers to specify the priority to wakeup nodes https://github.com/threefoldtech/tfgrid-sdk-go/issues/804
        - [x] https://github.com/threefoldtech/tfgrid-sdk-go/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afarmerbot
    - Testsuiite: https://app.testlodge.com/a/26076/projects/40893/suites/221831
- [x] pulumi
    - [x] support mycelium https://github.com/threefoldtech/pulumi-threefold/issues/255
    - [x] add more examples
- [ ] zos
    - [x] supporting compressed kernels threefoldtech/zos#2236 (also now supported by newer version from cloudhypervisor)
    - [x] stricter health checks for filtering nodes to deploy on threefoldtech/zos#2153
    - [x] display the right size in the microvm (not the full node disk size) https://github.com/threefoldtech/zos/issues/2007
    - [ ] tools to debug images/flists if they're bootable in zos threefoldtech/zos#2233
    - [x] zos able to download/mount flists over mycelium IPs https://github.com/threefoldtech/zos/issues/2338
    - [x] zos to support zdb over mycelium IPs https://github.com/threefoldtech/zos/issues/2338
    - [x] support HDD only nodes https://github.com/threefoldtech/zos/issues/2258

## Non Release Blocking Stories:
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1285

## Out of QA Team Scope
- https://github.com/threefoldtech/home/issues/1459
