### ISSUE TITLE
Support Deployments on ZOS4 nodes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1569]
We currently have tools and clients (e.g., Terraform, Pulumi and Go, TypeScript clients) that are built around ZOS3 features. With the introduction of ZOS4, we need to expand support for ZOS4-specific features while maintaining backward compatibility with ZOS3.

- [x] [Featureset RMB call](https://github.com/threefoldtech/zos/issues/2421)
- [x] [Indexing feature sets on the Grid Proxy](https://github.com/threefoldtech/tfgrid-sdk-go/issues/1209)
- [x]  [Golang client, tfrobot and cli integration](https://github.com/threefoldtech/tfgrid-sdk-go/issues/1213)
- [x] [Terraform Support](https://github.com/threefoldtech/terraform-provider-grid/issues/975)
- [x] [Pulumi Support](https://github.com/threefoldtech/pulumi-threefold/issues/517)
- [x] #1574 (to be done in 3.16)
- [x] [zos](https://github.com/threefoldtech/zos/issues/2378)

**Comment by xmonader** [comment]
The integration in Typescript and the Dashboard moved to #1574
