### ISSUE TITLE
gateway improvements

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#174]
- [ ] [Link local service discovery](https://github.com/threefoldtech/rivine/issues/518)
- [x] [Continuous bootstrap peer connection attempts](https://github.com/threefoldtech/rivine/issues/517)

While doing this, it might be worth to look into the addition of some extensive logging and/or metrics

- [x] [Slow transaction propagation](https://github.com/threefoldtech/rivine/issues/519)
This last issue might warrant a redesign of the gateway module

**Comment by jdelrue** [comment]
@LeeSmet can we close?

**Comment by GlenDC** [comment]
@jdelrue it is not finished yet. @LeeSmet updated the issue with the latest state.
