### ISSUE TITLE
tf_desktop_wallet_1.0.0 (July)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#348]
Project (automated kanban): <https://github.com/orgs/threefoldtech/projects/34>

Release Steps (as stories):
- [x] (1) 1st Alpha Version of 1.0.0 (`v0.1.0`): <https://github.com/threefoldtech/home/issues/349> (released on 11th of June, 2019: <https://github.com/threefoldfoundation/tfchain-wallet-electron/releases/tag/v0.1.0>);
- [ ] (2) 2nd Alpha Version of 1.0.0 (`v0.1.1`): <https://github.com/threefoldtech/home/issues/354> (**in progress**);
- [ ] (3) Beta Version of 1.0.0: <https://github.com/threefoldtech/home/issues/353> (later);
- [ ] (4) Release of 1.0.0: <https://github.com/threefoldtech/home/issues/350> (later);

> Individual issues/tasks are linked/listed as part of the actual release step-by-step story cards.

Product Repository: https://github.com/threefoldfoundation/tfchain-wallet-electron

Product Owners:
- [ Glen De Cauwsemaecker](http://github.com/glendc);
- [ Dylan Verstraete](http://github.com/dylanverstraete);

**Comment by GlenDC** [comment]
Will do the administrative work for this project, its stories and issues on Monday morning.

**Comment by GlenDC** [comment]
Tech Repo: https://github.com/threefoldfoundation/tfchain-wallet-electron

**Comment by GlenDC** [comment]
Closed, replaced by project-repo-based projects. Will add new story cards to reflect the current (reduced in scope) planning of this project.
