### ISSUE TITLE
TF Desktop Wallet v1.0.0-a1 (Demo)

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#349]
The alpha version of the TF Desktop Wallet, a manager to manage your TF wallets.

### Frontend:
Electron+ReactJS was chosen because:
- it is a mature and proven crossplatform technology;
- it allows us to utilise the extensive CSS/HTML/JS/ReactJS knowledge from people such as @DylanVerstraete;
- it will allow us to develop a desktop wallet rapidly, while still being easy enough to maintain;
- Urgent Tasks:
   - [x] setup the frontend project, starting from a bootstrap project;
   - [x] get flow correctly (account page, wallet page, login page, account creation page, account settings, wallet settings, transfer, ...;
   - [x] [add wallet receive screen, compatible with official Threefold App](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/7);
   - [x] allow setting custom network type for an account;
   - [x] implement new account page(threefoldfoundation/tfchain-wallet-electron#11)
   - [x] create wallet settings shortcut on account settings (threefoldfoundation/tfchain-wallet-electron#12)
- [x] full multisig support
- [x] a good UX
- [x] clear error handling

### Backend (backend a in black-box library, not a server):
- [x] provide JS (ES6) API:
  - [x] account, manages one or multiple wallets;
  - [x] wallet, owned by an account;
       - [x] provide stub API
       - [x] hook up real Wallet internally;
       - [x] look up actual balance;
       - [x] be able to get transaction (views) from a balance obj;
       - [x] be able to build transactions, sign and submit them;
   - [x] provide ES6 high-level test suite, using only the public API (as defined in api.py);
- ~port tfchain-go to JS using [GopherJS](https://github.com/gopherjs/gopherjs)~;
  - cancelled because we do not have that much light-client logic in Go;
  - [x] Port tfchain-py (python client pulled out of [JSX](http://github.com/threefoldtech/jumpscaleX)), using a Python (3.6) -> JS (ES6) transpiler (out of all projects listed [out there](https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js#python) most are toy projects, dead or both. Of the few remaining projects (technologies) only [Transcrypt](http://www.transcrypt.org) is an actual compiler (limiting as it may be), while the other projects are transpilers, [Brython](https://github.com/brython-dev/brython) being the only decent one even if not useful to our case):
     - [x] Polyfill all crypto logic using JS-native libraries, wrapped in a _thin_ Python API;
     - [x] Polyfill encoding logic (hex/base64/json/bin/str/int, written in JS-native code, wrapped in a _thin_ Python API;
     - [x] Polyfill the HTTP Request (Get/Post) logic, ~using the [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) _sync_ logic~ modern ES6 fetch/Request Promise-based API, written in JS-native code, wrapped in a _thin_ Python API;
     - [x] Polyfill some array primitives, written in JS-native code, wrapped in a _thin_ Python API;
     - [x] Polyfill async logic, using JS-native ES6 promises, such that we can make long-blocking calls async (e.g. those involving HTTP requests);
      - [x] Port ExplorerClient from tfchain-py;
      - [x] Port the crypto merkletree module from tfchain-py;
      - [x] Port errors module from tfchain-py;
      - [x] Port the siabin/rivbin encoders from tfchain-py;
      - [x] Port PrimitiveTypes module from tfchain-py;
      - [x] Port UnlockHash+UnlockHashType from tfchain-py;
      - [x] Port all remaining types from tfchain-py;
      - [x] Port the entire transactions module from tfchain-py;
         - [x] Base / Framework / Standard Transactions
         - [x] Minting Transactions
      - [x] Port the TFChainClient from tfchain-py;
         - [x] Standard Functionality
         - [x] Minting Functionality
      - [x]  Port the TFChainWallet from tfchain-py;
         - [x] Standard Functionality
         - ~Minting Functionality~ (moved to future release)
      - [x] Provide API for account balance to view transaction list
      - [x] Provide transaction builder for wallet API
      - [x] Turn balance call from account API into a promise
      - ~[provide a way to chain promises in the jsasync library](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/15)~ (cancelled)
      - [x] [be able to pool multiple promises together and stream loop results](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/16)
- [x] Port tfchain-py unit tests (that are relevant) to Transcryp'ed unit tests, wrapped in a ES6 Test Suite, so that we can automatically test the compiled code after each compilation;
    - [x] Decide on an ES6 Test Suite Framework for this that fits in our YARN/NPM Pipeline
    - [x] Port the encoding tests
    - [x] Port the non-transaction types tests
    - [x] Port the transactions tests
         - [x] Port the Standard transactions tests
         - [x] Port the Minting transactions tests
    - ~Port the High Level Unit Tests~ (moved to future release):
         - ~Client API Tests~
              - ~Client Standard API Tests~
              - ~Client Minting API Tests~
         - ~Wallet API Tests~
              - ~Wallet Standard API Tests~
              - ~Wallet Minting API Tests~

**Comment by GlenDC** [comment]
Deadline: Thursday 23rd Of May. That day a demo is planned as well via Zoom. Exact time TBD, (cc @despiegk, please let us know if you have an exact timing in mind).

**Comment by GlenDC** [comment]
@DylanVerstraete please add missing tasks to Frontend, keep it up to date and use it properly as a checklist for yourself. It will help you organise yourself.

**Comment by GlenDC** [comment]
> Deadline: Thursday 23rd Of May

This deadline was very tight and can sadly not be met. However great progress has been made. The current goal is to give a demo in the late afternoon on Monday the 27th of May for internal purposes via Zoom.

**Comment by GlenDC** [comment]
Demo moved to next week Monday as too many people are on holiday this week.

**Comment by GlenDC** [comment]
Also, besides the task list above, you can also track the tasks that have issues (and might perhaps not be tracked above) in the milestone: https://github.com/threefoldfoundation/tfchain-wallet-electron/milestone/1

First alpha will be released when this milestone is closed.

**Comment by GlenDC** [comment]
Alpha 1 release is ready and shipped. Installers available for MacOS, Windows and Linux: <https://github.com/threefoldfoundation/tfchain-wallet-electron/releases/tag/v0.1.0>

**Comment by GlenDC** [comment]
A demo will be held on Thursday the 13th of June, timing to be announced. Issue is complete though.
