### ISSUE TITLE
TF Desktop Wallet v1.0.0

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#350]
TBD once v1.0.0-beta is released and the demo has been given.

### Frontend
- Tasks:
   - [ ] add third-party credits to App (https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/6);
   - [ ] allow the listening of addresses and their balance as a separate screen from wallet (next to each address also put a receive button, so you can automatically go to the receive screen with that address selected)(https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/9);
   - [ ] allow setting different start index, name and address count for default address when creating account(https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/10);
   - [ ] allow setting custom explorer addresses (show in explanation that by default based on the network x, y, and z are used as explorers)(https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/10);
   - [ ] allow setting custom explorer addresses (show in explanation that by default based on the network x, y, and z are used as explorers)(https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/10);

### App:
- [ ] [ensure app wallet installer is upgradeable](https://github.com/threefoldfoundation/tfchain-wallet-electron/issues/5);

**Comment by GlenDC** [comment]
Tech Repo: https://github.com/threefoldfoundation/tfchain-wallet-electron

**Comment by GlenDC** [comment]
Closed, replaced by project-repo-based projects. Will add new story cards to reflect the current (reduced in scope) planning of this project.
