### ISSUE TITLE
web integration to 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#371]
- [ ] [blog](https://github.com/threefoldtech/jumpscaleX_threebot/issues/22)
- [ ] alerta
   -  [x] [alerta](https://github.com/threefoldtech/jumpscaleX_threebot/issues/20)
   -  [ ] improve ui and use jsx alertahandler (https://github.com/threefoldtech/jumpscaleX_core/issues/55)

- [x] myjobs
   - [x] [myjobs frontend/actors](https://github.com/threefoldtech/jumpscaleX_threebot/issues/19)
   - [x] [improve actors and ui ](https://github.com/threefoldtech/jumpscaleX_core/issues/57)

- [x] pastebin
   - [x] [actors/ui](https://github.com/threefoldtech/jumpscaleX_threebot/issues/21)

**Comment by xmonader** [comment]
alerta awaits PR review https://github.com/threefoldtech/jumpscaleX_core/pull/89

**Comment by xmonader** [comment]
continued here https://github.com/threefoldtech/home/issues/373
