### ISSUE TITLE
requirements for v10.1.1

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#394]
## Development

- [ ] [schema migrations](https://github.com/threefoldtech/jumpscaleX_core/issues/155)
- [ ] [threebot client auth](https://github.com/threefoldtech/jumpscaleX_core/issues/15)
- [ ] [3git](https://github.com/threefoldtech/home/issues/393)
- [ ] [Bugfixes for 10.1.1]()

# Testing

## ready to test
- [ ] [remaining verifications in 10.1.0](https://github.com/orgs/threefoldtech/projects/46) (in case of repoen change the milestone to 10.1.1)
- [ ] tests for [actor security](https://github.com/threefoldtech/home/issues/382)
- [ ] tests for [crud actors ](https://github.com/threefoldtech/home/issues/381)
- [ ] Automation Testing for wikis 
- [x] Sonic client

## blocked on code completion
- [ ] tests for schema migration
- [ ] tests for client auth

# Bugs
- [ ] [BCDB operational error](https://github.com/threefoldtech/jumpscaleX_core/issues/236)
- [ ] [BCDBFS: sonic out of sync](https://github.com/threefoldtech/jumpscaleX_core/issues/183)
- [ ] [name** value should always be present if defined in schema and not allow empty values in object creation](https://github.com/threefoldtech/jumpscaleX_core/issues/225) and (https://github.com/threefoldtech/jumpscaleX_core/issues/171)

- [ ] [can't start zdb instance](https://github.com/threefoldtech/jumpscaleX_core/issues/213)
- [ ] [Stopping threebot server](https://github.com/threefoldtech/jumpscaleX_core/issues/209)
- [ ] [Google API to be a core dep](https://github.com/threefoldtech/jumpscaleX_core/issues/197)
- [ ] [threebot-test bug](https://github.com/threefoldtech/jumpscaleX_core/issues/180)
- [ ] [remove package reflected on restart](https://github.com/threefoldtech/jumpscaleX_core/issues/149)
- [ ] [startup cmd bugs](https://github.com/threefoldtech/jumpscaleX_core/issues/102)
- [ ] [sonic builder](https://github.com/threefoldtech/jumpscaleX_builders/issues/37)
- [ ] [gedis client bug](https://github.com/threefoldtech/jumpscaleX_core/issues/242)
- [ ] [zdb client bugs](https://github.com/threefoldtech/jumpscaleX_core/issues/247)
- [ ] [web resources cleanup](https://github.com/threefoldtech/jumpscaleX_core/issues/156)

**Comment by Dina-Abd-Elrahman** [comment]
Done with sonic client.

### Related issues:

https://github.com/threefoldtech/jumpscaleX_core/issues/250
https://github.com/threefoldtech/jumpscaleX_core/issues/269
https://github.com/threefoldtech/jumpscaleX_core/issues/270
https://github.com/threefoldtech/jumpscaleX_core/issues/271
https://github.com/threefoldtech/jumpscaleX_core/issues/272

**Comment by rkhamis** [comment]
Closing this storycard for being too broad. Has been broken down into smaller stories:

 - [ ] https://github.com/threefoldtech/home/issues/417
 - [ ] https://github.com/threefoldtech/home/issues/402
 - [ ] https://github.com/threefoldtech/home/issues/393
