### ISSUE TITLE
myjobs improvements [development_myjobs]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#395]
- [x] re-introduce return queue concept
    - allows to launch jobs and results are posted in return queue with specified name
    - allows developers to create multiple pipelines and wait
    - the worker posts the result in right return queue, which allows any job object to see if finished
    - don't forget to cleanup queues if user does not do, otherwise mem leak
    - implement test7
    - resolves [bug 235](https://github.com/threefoldtech/jumpscaleX_core/issues/235)
    - see function ```wait_queue``` on factory
- [x] wait should be implemented using queues in redis ```return queue concept```
- [x] bug: wait with die does not work see [237](https://github.com/threefoldtech/jumpscaleX_core/issues/237)
- [ ] change 3bot server to use subprocess mode. (@serboctor ) and do tests threefoldtech/jumpscaleX_core#335
- [x] test 10 not working properly (subprocess not done i time)
- [x] tests not working well, when error does not exit when using subprocess (see test 10)
- [x] remove data consistency issues threefoldtech/jumpscaleX_core#323
- [x] Myjobs tests fail threefoldtech/jumpscaleX_core#342

## to check if issue if yes fix

- [ ] wait on myjobs threefoldtech/jumpscaleX_core#235

**Comment by despiegk** [comment]
see /Users/despiegk/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/myjobs/tests/10_workers.py

on development_3git branch

should also work, port to this branch

**Comment by Hamdy** [comment]
@despiegk  this part not clear enough, please elaborate!
```
    - the worker posts the result in right return queue, which allows any job object to see if finished
```
