### ISSUE TITLE
BCDB 10.2 [development_bcdb2]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#398]
## generic issues

- [x] move relevant improvements from branch development_bcdb to development_bcdb2
    - don't remove all the performance tests overload
    - only the things we need, close the development_bcdb branch
    - if anything to do with jumpscale stability move to development_fixes branch !!!
    - if anything with master slave move o development_bcdb3 branch (is for future)
- [x] remove the [shortcut fix](https://github.com/threefoldtech/jumpscaleX_core/commit/4409a78552b0915ff671c5217c08e280ffabd0d4) (ignore index inconsistencies fix) needs to be removed
- [x] fix index inconsistency properly (doesn't happen now on on myjobs branch *merged already*)
- [x] need some performance tests threefoldtech/jumpscaleX_core#333
- [x] support for multi processes threefoldtech/jumpscaleX_core#324
- [x] Refactor BCDB threefoldtech/jumpscaleX_core#354

### checks

- [x] write/delete shouldn't return ok until the data processor greenlet is done threefoldtech/jumpscaleX_core#325
- [x] update behaviour obj threefoldtech/jumpscaleX_core#171

## related issues

- [x] threefoldtech/jumpscaleX_core#333

**Comment by abom** [comment]
The error of `cannot find obj with id` is reproducible after stopping the container.

Start the container, then start theebot using e.g. `j.servers.threebot.local_start_default()`, then stop the container `docker stop 3bot`, then start the container and threebot again, will give:

```
un 08 16:15:51 ta/bcdb/BCDBModel.py - 494 - get                                : EXCEPTION: 
    could not find obj with id:74 of jumpscale.myjobs.job
--TRACEBACK------------------
<string> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreeBotServersFactory.py in local_start_default
    90    client = self.default.start(background=background, packages=packages)
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreebotServer.py in start
    214    j.servers.myjobs.reset_data()
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in reset_data
    512    self.jobs.reset()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in reset
    190    for item in self.find():
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in find
    248    item = self.get(id=id, reload=reload, autosave=False)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in get
    115    rc, jsconfig = self._get(name=name, id=id, die=needexist, reload=reload)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _get
    151    obj = self._model.get(id)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py in wrapper_queue_method
    60    res = func(*args, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py in get
    494    raise j.exceptions.NotFound(f"could not find obj with id:{obj_id} of {self.schema.url}")
-----------------------------
```

**Comment by waleedhammam** [comment]
- An issue related to database lock happens when 2 processes try to acces the same database
- full stacktrace

- reproduce with start threebot server, close it, start it again
```
reebot.package.1
Mon 09 09:35:03 ata/peewee/peewee.py -3069 - execute_sql                        : EXCEPTION: 
    OperationalError('database is locked',)
--TRACEBACK------------------
<string> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreeBotServersFactory.py in local_start_explorer
    67    return self.local_start_default(background=background, packages=packages, reload=reload)
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreeBotServersFactory.py in local_start_default
    91    client = self.default.start(background=background, packages=packages)
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreebotServer.py in start
    265    self._packages_core_init()
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreebotServer.py in _packages_core_init
    367    p = j.tools.threebot_packages.get(name=name2)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in get
    115    rc, jsconfig = self._get(name=name, id=id, die=needexist, reload=reload)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _get
    164    res = self.find(name=name)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in find
    248    item = self.get(id=id, reload=reload, autosave=False)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in get
    115    rc, jsconfig = self._get(name=name, id=id, die=needexist, reload=reload)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _get
    151    obj = self._model.get(id)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py in wrapper_queue_method
    60    res = func(*args, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py in get
    490    data = self.storclient.get(obj_id)
/sandbox/lib/jumpscale/Jumpscale/clients/stor_sqlite/DBSQLite.py in get
    102    if len(res) == 0:
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in __len__
    1960    self._ensure_execution()
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in _ensure_execution
    1942    self.execute()
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in inner
    1856    return method(self, database, *args, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in execute
    1930    return self._execute(database)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in _execute
    2098    cursor = database.execute(self)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in execute
    3082    return self.execute_sql(sql, params, commit=commit)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in execute_sql
    3076    self.commit()
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in __exit__
    2831    reraise(new_type, new_type(*exc_args), traceback)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in reraise
    196    raise value.with_traceback(tb)
/sandbox/lib/jumpscale/Jumpscale/data/peewee/peewee.py in execute_sql
    3069    cursor.execute(sql, params or ())
-----------------------------

3BOTDEVEL:3bot:~:
```

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/jumpscaleX_core/issues/318 is needed for performance tests

**Comment by waleedhammam** [comment]
also database is locked: https://github.com/threefoldtech/jumpscaleX_core/issues/320

**Comment by xmonader** [comment]
import export needs to be re-implemented

**Comment by john-kheir** [comment]
All related tickets are closed.
