### ISSUE TITLE
tcprouter client [development]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#406]
## idea
![image](https://user-images.githubusercontent.com/64129/69140633-86893800-0acb-11ea-8d2e-4c6051146d3c.png)

- create small network component which lives in container
- this component connects to tcprouter and allows sockets to be backchanneled into the container

## todo

- [x]  #405 (tcprouter repo move)
- [x] specs
- [x] builder in jumpscale
- [x] make sure is part of our base docker image [code added [here](https://github.com/threefoldtech/home/issues/406#issuecomment-558067389) but image creation blocked until the branch is merged]
- [x] make jumpscale client for it so it can make the connection to the tcprouter

**Comment by xmonader** [comment]
- @zaibon implemented the client already https://github.com/xmonader/tcprouter/pull/8

I still have to finish off the work on the server side.

**Comment by xmonader** [comment]
It's code complete now and in ongoing testing by @zaibon

**Comment by waleedhammam** [comment]
tcp router builder is done at: https://github.com/threefoldtech/jumpscaleX_builders/commit/4ff237db1f6b8e3ef5cc71443195bd6b10e06ea8

**Comment by despiegk** [comment]
is not code complete, see main part

**Comment by waleedhammam** [comment]
add tcprouter to be part of the docker installation image: https://github.com/threefoldtech/jumpscaleX_core/commit/028482ec9d1598c268be7b322753b279ef3af258

**Comment by waleedhammam** [comment]
add tcprouter jumpscale client at: https://github.com/threefoldtech/jumpscaleX_core/commit/d12bc49e1ca4ceec37e12f7520738f714d365815

how to use at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_actorsimprovement/JumpscaleCore/clients/tcprouter/README.md

**Comment by Dinaamagdy** [comment]
tcprouter builder doesn't work 
```
        ++ LANG=en_US.UTF-8
        + cd /sandbox/go_proj/src/github.com/threefoldtech/tcprouter
        + make all
        main.go:9:2: cannot find package "github.com/cenkalti/backoff/v3" in any of:
                /sandbox/go/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
                /sandbox/go_proj/src/github.com/cenkalti/backoff/v3 (from $GOPATH)
        make: *** [client] Error 1
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/BuilderBaseClass.py in wrapper_action
    163    builder.build()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/BuilderBaseClass.py in wrapper_action
    178    res = self.apply_method(func, kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/BuilderBaseClass.py in apply_method
    93    return func(**kwargs)
/sandbox/lib/jumpscale/JumpscaleBuilders/network/BuilderTCPRouter.py in build
    28    self._execute(build_cmd)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/BuilderBaseClass.py in _execute
    387    retry=retry,
/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py in execute
    117    retry=retry,
/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py in execute
    2304    raise Tools.exceptions.Base(msg)
-----------------------------

```

**Comment by andrewayoub** [comment]
fixed here https://github.com/threefoldtech/jumpscaleX_builders/pull/41

**Comment by despiegk** [comment]
please move doc to right repo and close this one

**Comment by AhmedHanafy725** [comment]
> add tcprouter jumpscale client at: [threefoldtech/jumpscaleX_core@d12bc49](https://github.com/threefoldtech/jumpscaleX_core/commit/d12bc49e1ca4ceec37e12f7520738f714d365815)
> 
> how to use at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_actorsimprovement/JumpscaleCore/clients/tcprouter/README.md

**For the client**
- Is it suppose to have only one instance? as it starts the client in `tmux` session with the same name so I can't make another instance to run at the same time.
- I think it is better if we make a use of schema checking for `local_address` and `remote_address` by separating the `address` and `port` into two different variables.

**Comment by waleedhammam** [comment]
> > add tcprouter jumpscale client at: [threefoldtech/jumpscaleX_core@d12bc49](https://github.com/threefoldtech/jumpscaleX_core/commit/d12bc49e1ca4ceec37e12f7520738f714d365815)
> > how to use at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_actorsimprovement/JumpscaleCore/clients/tcprouter/README.md
> 
> **For the client**
> 
> * Is it suppose to have only one instance? as it starts the client in `tmux` session with the same name so I can't make another instance to run at the same time.
> * I think it is better if we make a use of schema checking for `local_address` and `remote_address` by separating the `address` and `port` into two different variables.

Yes, Only one instance should be running a time.

and seperated addresses into ips and ports as suggested at: https://github.com/threefoldtech/jumpscaleX_core/commit/8c7aecd3030b117034730c85ede51c022cf282a1

**Comment by AhmedHanafy725** [comment]
**verified**
branch: development_fixes
commit: https://github.com/threefoldtech/jumpscaleX_core/commit/8c7aecd3030b117034730c85ede51c022cf282a1
it is working fine
![image](https://user-images.githubusercontent.com/41957921/70702697-56eadb80-1cd7-11ea-9d65-15a1004e71f4.png)
![image](https://user-images.githubusercontent.com/41957921/70702777-80a40280-1cd7-11ea-89bc-1551fc8234bb.png)
