### ISSUE TITLE
ThreeBot Connect v???

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#413]
## what is

- mobile app for ios & android 
## features

- [ ] wallet for TFT
- [ ] authentication towards our services
- [ ] FFP/Circles ... integrated with TB Connect
- [ ] 3bot web/ wiki/chatbot can use TB Connect to recognise people
- [ ] link to registration webpage

## todo

- [ ] define version
- [ ] need some decent exposure with our community
- [ ] define, what is deadline and what can we expect
