### ISSUE TITLE
FileManager ThreeBot [development_threetransfer]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#414]
## what

Filemanager in 3bot usable.

## features

- [ ] web interface
  - [ ] Put sourcecode in the repo (without packages)
  - [ ] Adjust routes
- [x] webdav interface
    - [x] can mount over fuse
- [x] BCDB FS = filesystem implemented on top of BCDB
- [x] stored in BCDB FS
- [x] JSX client to manipulate BCDB FS
- [x] JSX tool to choose any path and generate GUID
- [x] expose GUID to files or dir in web interface (bottle server?):  
   - [ ] when dir $threebot/files/$name_$guid.zip download as zip 
   - [x] when file: $threebot/files/$name_$guid.extension download file in browser
   - [ ] when dir $threebot/files/$name_$guid show UI to show dirstructure, read only !

## todo

- [ ] some performance tests of multiple components
- [ ] some scaling tests e.g. store 100k small files in dir structure

## Out of scope

- only office integration

**Comment by jdelrue** [comment]
Merged with https://github.com/threefoldtech/home/issues/414
