### ISSUE TITLE
As a fileserver user, create short links for download  [development_web]

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#432]
# Usecase
When uploading files through webdav it should be easy to create short links from it.

## requirements (jonas did some work here)

- [x] webdav interface
    - [x] can mount over fuse
- [x] BCDB FS = filesystem implemented on top of BCDB
- [x] stored in BCDB FS
- [x] JSX client to manipulate BCDB FS
- [x] JSX tool to choose any path and generate GUID
- [x] expose GUID to files or dir in web interface (bottle server):  
   - [x] when dir $threebot/files/$name_$guid.zip download as zip 
   - [x] when file: $threebot/files/$name_$guid.extension download file in browser
   - [ ] when dir $threebot/files/$name_$guid show UI to show dirstructure in filemgr, read only !

## todo

- [ ] some performance tests of multiple components
- [ ] some scaling tests e.g. store 100k small files in dir structure

## specs remarks

- the GUID is a hash of a GUID generated when link asked for
- link need to be remembered in a BCDB from package threebot/fileserver
- the path of file is always $3botbase/files/$hash__$name.$ext
- need bottleserver to serve this 
- files are stored in our BCDBFS

## how to use

```python
cl = j.clients.threebot...
guid=cl.files.upload(src="localpath/somefile.txt",dest="/myfiles/somefile.txt")
cl.files.download(src="/myfiles/somefile.txt",dest="localpath/somefile.txt")
cl.files.download(guid=guiddest="localpath/somefile2.txt")
#TODO: do a test to verify file downloaded

link=cl.files.link_get(path="/myfiles/somefile.txt",name=None) 
#if name not specified then will be basename of file in this case somefile
#link is something like: https://kristof.3bot.tfgrid.org/files/aabbccddeeffgghh__somefile.txt
#note how we put the __ after the hash

# for a directory
guid=cl.files.upload(src="localpath/",dest="/myfiles/",ignore=...) #all files will be uploaded with subdirs
link=cl.files.link_get(path="/myfiles/",name="group_of_files") 
#link is something like: https://kristof.3bot.tfgrid.org/files/aabbccddeeffaaaa__group_of_files.zip

#get webdav filemount
cl.files.mount(path="/myfiles/","/tmp/my3botfs")

#create shortcut link (basically overrule the std hash behaviour, create own link)
link=cl.files.link_get(path="/myfiles/somefile.txt",url="myfile.txt") 
#link is now https://kristof.3bot.tfgrid.org/files/myfile.txt
link=cl.files.link_get(path="/myfiles/somefile.txt",url="somepath/myfile.txt") 
#link is now https://kristof.3bot.tfgrid.org/files/somepath/myfile.txt


```

## Out of scope

- only office integration
- UI see threefoldtech/home#464

**Comment by despiegk** [comment]
howcome verification if I see items not done yet above?

**Comment by xmonader** [comment]
@jdelrue @despiegk what is the status here and what is needed?

**Comment by tobiaschielens** [comment]
After my last update we did not do any furthur work on this issue.

The tasks that are not checked still need to be done. 
For me this can indeed be moved to `todo`

**Comment by sasha-astiadi** [comment]
@ken-de-moor
