### ISSUE TITLE
cleanup base actors/chatflows

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#441]
## move to packages

on j.tools.threebot the actors & chatflows there dont need to be there

- [x] chatflows: threefoldtech/jumpscaleX_threebot#281
    - [x] chatbot actor: threefoldtech/jumpscaleX_threebot#284
- [x] team actors: threefoldtech/jumpscaleX_threebot#285
- [x] base actors: threefoldtech/jumpscaleX_threebot#283 : why and where needed?
- [x] package manager: threefoldtech/jumpscaleX_threebot#282

## some issues with packages

- [x] list on package managerr: threefoldtech/jumpscaleX_threebot#279
- <strike>[ ] name manager threefoldtech/jumpscaleX_threebot#277 (won't solve in this  story as it requires more work to resetup the infra -setup scripts are outdated, update the actors, and retest)</strike>

**Comment by xmonader** [comment]
packagemanager actor is moved into zerobot/base package

**Comment by john-kheir** [comment]
All tickets for this story are verified .. so closing it
