### ISSUE TITLE
k8s 0-OS integration: phase 1 [fcvm]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#449]
This story is the beginning of the work regarding the support of k8s on 0-OS. This effort will be spitted in multiple phases. Each phase will bring its set of features.

preliminary research document: https://docs.google.com/document/d/1XiYKcy8eDAfmGwBwF8bCQ0P57hJVg-7gQ53eLZGmROk/edit#

Phases 1.
- k8s running in a VM

Deliverable:
- Possibility to reserve a VM on a node for a k8s usage
- Possibility to configure a set of k8s VM and configure them into a cluster

Acceptance criteria:
- One a cluster is deployed, the client/sysadmin should be able to execute kubectl commands to its cluster.

Tasks:
- [ ] [Research exact network requirements](https://github.com/threefoldtech/zos/issues/436)
- [x] [k8s: prepare hardware for tests](https://github.com/threefoldtech/zos/issues/437)
- [x] [0-OS: implement VM](https://github.com/threefoldtech/zos/issues/6)
- [ ] 0-OS: add public ip reservation primitive
- [x] k8s: Create and Deploy basic resources (Pods, multi container pods, deployment, replicaset, secrets, configmap ) :heavy_check_mark: k3os
- [x] k8s: Create Services with clusterIP and NodePort :heavy_check_mark: k3os
- [x] k8s: Create PV and PVC with local path :heavy_check_mark: k3os
- [x] k8s: Create and Deploy prometheus monitoring with helm :heavy_check_mark: k3os
- [ ] k8s: Test different CNI provider
- [ ] k8s: Create and Deploy Storage solution (PV, PVC)
  - [x] local path :heavy_check_mark: k3os
  - [x] longhorn :boom: iscsiadm/open-iscsi must be installed on the host :heavy_check_mark: k3os
  - [x] Rook :heavy_check_mark: k3os
  - [x] Rook NFS :boom: need nfs-common
  - [x] Rook CEPH :boom: need rdb module and higher kernel :heavy_check_mark: k3os
  - [x] Rook cockroach
  - [x] Rook minio
- [x] k8s: Create and Deploy Ingress Controllers :heavy_check_mark: k3os
- [ ] k8s: Create and Deploy cert manager with helm
- [ ] k8s: Create and Deploy applications (CI/CD, multi tier)
- [ ] k8s: Create and Deploy an HA cluster
- [x] k8s: Test monitoring :heavy_check_mark: k3os
- [x] k8s: Test logging
- [ ] k8s: Test security
- [ ] k8s: Final report

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zos/pull/487
