### ISSUE TITLE
Make green run for jumpscalex  tests [development_green_run]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/home#453]
## deliverables

- [ ] tests done as specified below and ok
- [x] documentation: where can we see these tests are ok
https://github.com/threefoldtech/jumpscaleX_core
- [x] results of tests, where to see
https://github.com/threefoldtech/jumpscaleX_core
## questions

put answers in core repo of jumpscale

- [x] where is branch specified?
- [x] when run?
- [x] who runs it?
all in CI : https://github.com/threefoldtech/jumpscaleX_core

## tests which need to be ok

- [ ] servers
    - [x] openresty_tests  https://github.com/threefoldtech/jumpscaleX_core/issues/364 
    - [x] myjobs tests threefoldtech/jumpscaleX_core#342
    - [x] imap_server threefoldtech/jumpscaleX_libs#41
- [x] Installation 
- [x] SAL
- [x] clients (sonic threefoldtech/jumpscaleX_core#250 )
- [x] BCDB 
    - [x] threefoldtech/jumpscaleX_core#331
    - [x] threefoldtech/jumpscaleX_core#340
- [x] baseclass config tests threefoldtech/jumpscaleX_core#357

### Libs_extra

- [ ] radicale server (to check @Hamdy ) 
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/197
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/193
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/198

### Threebot

- [x] wikis (high)[ threefoldtech/jumpscaleX_threebot#309 ]
- [ ] phonebook (high)
    - [ ] https://github.com/threefoldtech/jumpscaleX_core/issues/326
- [x] workloadmanager (high)
- [x] directory (high)
- [x] web_interface 
   - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/316
### Builders

- [x] web 
    - [ ] threefoldtech/jumpscaleX_builders#44 
    - [ ] threefoldtech/jumpscaleX_builders#43
- [x] zdb
- [x] sonic

**Comment by Dinaamagdy** [comment]
finish servers :
```
 ok

----------------------------------------------------------------------
Ran 50 tests in 126.738s

OK (SKIP=35)
```
code : https://github.com/threefoldtech/jumpscaleX_core/tree/development_green_run/JumpscaleCore/servers/tests

**Comment by Dinaamagdy** [comment]
Sal already has green run 
```
specifically, section 10.2.3 ("Information Requirements").
.
----------------------------------------------------------------------
Ran 92 tests in 84.819s

OK (SKIP=4)
```

**Comment by Dinaamagdy** [comment]
Installation finished 
clients: finished except sonic client

**Comment by Dinaamagdy** [comment]
add new tests to be green 
- bcdb test 
estimation time : so increase estimation time to more one working day

**Comment by despiegk** [comment]
where are the tests, how can we see them running, ...

**Comment by despiegk** [comment]
we need to limit this story to tests we can finish in days, we want to release jumpscale 10.2.x

**Comment by xmonader** [comment]
lapis, apache2, caddy aren't used and can't block the release please skip them

**Comment by xmonader** [comment]
- please pause on phonebook (still to be figured out)
- webinterface tests needs to be updated 
- directory and workloads : check with @serboctor

**Comment by xmonader** [comment]
- phonebook and authentication https://github.com/threefoldtech/jumpscaleX_core/issues/326

**Comment by Dinaamagdy** [comment]
green run in jumpscale core :
https://github.com/threefoldtech/jumpscaleX_core

**Comment by Dinaamagdy** [comment]
all checked now except which have issues , u can find issues beside it 
please @xmonader  define which one will be solved in this milestone and which will postpone to next milestone

**Comment by Dinaamagdy** [comment]
will close this issue as it was for 10.2 and will work on this https://github.com/threefoldtech/home/issues/480 for 10.3
