### ISSUE TITLE
bugfixes jumpscale 10.2 [development_fixes]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#458]
groups bugfixes to do now on jumpscale 10.2 which are not a feature or part of other well defined story

- [x] too many packages loaded threefoldtech/jumpscaleX_core#336
- [x] schema's return wrong for gedis: threefoldtech/jumpscaleX_core#322
- [x] fix bcdb tests threefoldtech/jumpscaleX_core#340 
- [x] create a package to create crud actors for bcdb system models threefoldtech/jumpscaleX_core/issues/345
- [x] autocomplete in shell does not work when names have .  threefoldtech/jumpscaleX_core#289
- [x] keyload msg in ssh agent threefoldtech/jumpscaleX_core/issues/312
- [x] restore lazy loading threefoldtech/jumpscaleX_core#337
- [x] lazily load packages threefoldtech/jumpscaleX_core#353
- [x] does bcdb work properly with greenlet to return ok : threefoldtech/jumpscaleX_core#325 (done by @despiegk )
- [x] generate error in multilevel-gen threefoldtech/jumpscaleX_core#287
- [x] base classes test: threefoldtech/jumpscaleX_core#245
- [x] index wants to create table in a bcdb readonly process https://github.com/threefoldtech/jumpscaleX_core/issues/365
- [x] reset and initializing system objects https://github.com/threefoldtech/jumpscaleX_core/issues/368
- [x] usage of gedis client: threefoldtech/jumpscaleX_core#339
