### ISSUE TITLE
As a 3bot FE user, install packages from js console

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#469]
As a 3bot user you should be able to install packages straight from the JS console of the UI

**Prerequisites**
modular, non-webpack 3bot ui should be included in packages

Example:
```
installPackage('somegithuburl');
```

It should also be possible with packages allready in the 3bot repo, maybe we could do something like
```
installPackage('3bot.calendar')
```

We would probably need an actor for this, it can be in the 'interface package' which makes most sense. 

**TODO**
- [x] Create dummy package in foreign, 'demo package' repo that we can install
- [x] Create actors to install package in your 3bot (or check if it exists already somwhere)
- [x] Create js functions to call
- [x] After installing a package, UI should probably poll to backend to see if it is added already

**DOD**
- User can add package to 3bot from frontend UI JS console
- Package gets added to menu on the left

**Comment by jdelrue** [comment]
Will be postponed; new 3bot version has no store yet
