### ISSUE TITLE
Bugfixes on JSX_Core for 10.3 not solved in 10.2 [development_fixes103]

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#472]
Contains less urgent bugfixes in JSX Core inventory : 

- [x] Inconsistent behaviour for sonic client threefoldtech/jumpscaleX_core#250
- [x] ZDB client bugs threefoldtech/jumpscaleX_core#247
- [x] No way to stop default threebot threefoldtech/jumpscaleX_core#209
- [x] error isconnected ppty in ssh client threefoldtech/jumpscaleX_core#206
- [x] Installer conflict threefoldtech/jumpscaleX_core#198
- [x] Installation behavior threefoldtech/jumpscaleX_core#189
- [x] tmp Install threebotbuilder threefoldtech/jumpscaleX_core#184
- [x] Installation issue threefoldtech/jumpscaleX_core#182
- [x] Value stored as string threefoldtech/jumpscaleX_core#162
- [x] error in ssh client threefoldtech/jumpscaleX_core#160
- [x] etcd server threefoldtech/jumpscaleX_core#158
- [x] Remove package from 3bot server threefoldtech/jumpscaleX_core#149
- [x] startupcmd tests threefoldtech/jumpscaleX_core#102
- [x] startupcmd threefoldtech/jumpscaleX_core#101
- [x] schema reload real-time threefoldtech/jumpscaleX_core#343
- [x] atexit handlers registration threefoldtech/jumpscaleX_core#351
- [x] issue loading registry package threefoldtech/jumpscaleX_core#369
- [x] sonic builder improvments https://github.com/threefoldtech/jumpscaleX_builders/issues/37
- [x] fix alerthandler test https://github.com/threefoldtech/jumpscaleX_core/issues/483 
- [x] Review Radicale usage https://github.com/threefoldtech/jumpscaleX_threebot/issues/349 
- [x] openresty https://github.com/threefoldtech/jumpscaleX_core/issues/502
- [x] parameterize package install https://github.com/threefoldtech/jumpscaleX_core/issues/502
- [x] capnp/nacl tests https://github.com/threefoldtech/jumpscaleX_core/issues/482
- [x] lapis server doesn't show up in tmux https://github.com/threefoldtech/jumpscaleX_core/issues/479
- [x] 3git config to be stored in configmanager instead of filesystem. https://github.com/threefoldtech/jumpscaleX_core/issues/467
- [x] Fix server rack tests https://github.com/threefoldtech/jumpscaleX_core/issues/508
- [x] Fix restic tests https://github.com/threefoldtech/jumpscaleX_core/issues/497

**Comment by hossnys** [comment]
all issues mentioned above fixed and verified
