### ISSUE TITLE
Unplanned bugfixes (low prio)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#473]
## List of bugs 

- [ ] syncer tool - pattern match https://github.com/threefoldtech/jumpscaleX_core/issues/142
- [x] ZDB client threefoldtech/jumpscaleX_core#247
- [x] empty wiki repo threefoldtech/jumpscaleX_threebot#249

**Comment by xmonader** [comment]
closing
