### ISSUE TITLE
Improvement proposals and bugfixes on JSX_Threebot for 10.3

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#476]
## Open bugs

- [x] sonic actor wrong threefoldtech/jumpscaleX_threebot#289
- [ ] workers stopped threefoldtech/jumpscaleX_threebot#192

## improvement features

- [ ] Gedis big response threefoldtech/jumpscaleX_threebot#74
