### ISSUE TITLE
November bugs and issues

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#49]
- [x] [Wallets page asks to update the app while already at the latest version](https://github.com/threefoldfoundation/tf_app/issues/379) Tf app issue, 
    Rob: Works now but I don't like the "fix", escalated. todo: 1h follow up
- [x] [Transaction confirmation screen is empty](https://github.com/threefoldfoundation/tf_app/issues/380)
- [x] [Testnet web explorers cannot handle the rendering all pages](https://github.com/threefoldfoundation/tfchain/issues/212):
   - [x] Todo: initial attempt: 2h
- [x] [Update release targets in makefiles to upload to the new hub](https://github.com/threefoldfoundation/tfchain/issues/210): 2h
- [x] [main explorer and testnet explorer down](https://github.com/threefoldfoundation/tfchain/issues/215): 2h

**Comment by LeeSmet** [comment]
- [x] (Update bootstrap/explorer nodes so they all run the same zero os version)[https://github.com/threefoldfoundation/tfchain/issues/209]
