### ISSUE TITLE
3bot server and bcdb stabilization [development_fixes2]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#495]
- [ ] 3bot server start/stop problems https://github.com/threefoldtech/jumpscaleX_core/issues/383
- [x] bcdb stress testing https://github.com/threefoldtech/jumpscaleX_core/issues/384
- [x] failing schema tests https://github.com/threefoldtech/jumpscaleX_core/issues/376
- [x] Fix bcdb index rebuild https://github.com/threefoldtech/jumpscaleX_core/issues/390
- [ ] random schema error during index rebuild https://github.com/threefoldtech/home/issues/496
