### ISSUE TITLE
Prepare TFT transition to Stellar [development_stellar_client]

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#500]
Github repo:[threefoldfoundation/tft-stellar](https://github.com/threefoldfoundation/tft-stellar)
TODO's:
- [x] Define reason

- [x] [Support blocking accounts](https://github.com/threefoldfoundation/tfchain/issues/383)
    - [x] Release  [ rivine v1.3](https://github.com/threefoldtech/rivine/projects/6)
    - [x] [tfchain 1.3-rc2 release broken on testnet](https://github.com/threefoldfoundation/tfchain/issues/387)
   - [x] Release tfchain v1.3
- [x] Convert rivine/research/stellar/examples to other languages:
   - [x] [javascript](https://github.com/threefoldtech/rivine/issues/633)
   - [x] [python](https://github.com/threefoldtech/rivine/issues/632)
- [x] [Add tft on Stellar to Jumpscale](https://github.com/threefoldtech/jumpscaleX_libs/issues/52)
- [x] Define multisig on issuing and distribution accounts
- [x] [Host token information on the testnet home domain for Discoverablity and Meta information](https://github.com/threefoldfoundation/tft-stellar/issues/1)  
- [x] Create script for the custom asset creation
    - [x] Modify to use Jumpscale
- [x] [Testnet faucet](https://github.com/threefoldfoundation/tft-stellar/issues/5)
- [x] [Spec locked tokens](https://github.com/threefoldtech/home/issues/500)
- [x] [Add time locked token support to the jumpscale  stellar wallet](https://github.com/threefoldtech/jumpscaleX_libs/issues/58)
- [x] [Add multisig support to Jumpscale](https://github.com/threefoldtech/jumpscaleX_libs/issues/107)
- [x] Conversion
   - [x] [Spec conversion from tfchain to the Stellar platform](https://github.com/threefoldfoundation/tft-stellar/issues/2)
   - [x] [Possibility to check via the explorer if an address is locked](https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/conversion/locking.md#distinction-between-locked-and-unlocked-addresses)
  -  [x] Is it possible to make the distinction between a Rivine and a Stellar address?->yes
  -  [x] [Conversion service](https://github.com/threefoldfoundation/tft-stellar/issues/11)
- [x] [Define transaction fee funding](https://github.com/threefoldfoundation/tft-stellar/issues/3)
- [x] [Create a tft transaction funding service](https://github.com/threefoldfoundation/tft-stellar/issues/25)
  - [x] [Charge 0.1 TFT in the transactionfundingservice](https://github.com/threefoldfoundation/tft-stellar/issues/35)
- [x] [Service for unlock transactions](https://github.com/threefoldfoundation/tft-stellar/issues/12)
- [x] [Deploy testnet services](https://github.com/threefoldfoundation/tft-stellar/issues/18)
- [x] [Limit access to gedis](https://github.com/threefoldfoundation/tft-stellar/issues/22)
- [x] [Keep threebot server running](https://github.com/threefoldfoundation/tft-stellar/issues/23)
- [x] [Spec new account activation](https://github.com/threefoldfoundation/tft-stellar/issues/33)
