### ISSUE TITLE
Fix bugs in Wallet

### ISSUE THREAD

**Issue by coeneivan** [threefoldtech/home#514]
- [x] [Locked transactions that have been unlocked, still show under the locked tab. #10
](https://github.com/threefoldtech/3bot_wallet/issues/10)

- [x] [After a transaction, the originating account is shown as having 0 tokens until the transaction completes. #9 
](https://github.com/threefoldtech/3bot_wallet/issues/9)

- [x] [When adding a wallet with duplicate name, the user is not informed why the wallet creation fails. #8
](https://github.com/threefoldtech/3bot_wallet/issues/8)

- [x] [Validation is being done before trimming spaces, allowing users to create wallets with blank names or duplicate names by adding spaces. #7
](https://github.com/threefoldtech/3bot_wallet/issues/7)

**Comment by jdelrue** [comment]
Bugs to be checked in new version @MathiasDeWeerdt
