### ISSUE TITLE
Fixing bugs in 3Bot connect app

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/home#515]
- [x] [Pin code can be bruteforced, no max tries or timeout. Should have a 3 tries limit and timeout.](https://github.com/threefoldtech/3Bot_connect/issues/23)

- [x] Authentication screen should be separated from all other components and refactored. 

- [x] When logging in, double tapping the emoji causes a black screen in the app.(https://github.com/threefoldtech/3Bot_connect/issues/43)

- [x] [Scanning QR on wallet while having the keyboard open does not close the keyboard, after closing keyboard the QR scan fails.](https://github.com/threefoldtech/3Bot_connect/issues/42)

- [x] Sorting out naming convention in the 3Bot Connect app.
