### ISSUE TITLE
Fix the following bugs in the 3botconnect app.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#528]
- [x] [When the user picks the wrong emoji, the authentication doesn't stop. #77](https://github.com/threefoldtech/3Bot_connect/issues/77)

- [x] [When trying to log in on firefox mobile, the login flow fails because the 3bot connect app opens in the browser instead of opening the app itself. #66](https://github.com/threefoldtech/3Bot_connect/issues/66)

- [x] [When disabling background activities ( develop options ) the login flow from mobile browser to app does not work at all. #65](https://github.com/threefoldtech/3Bot_connect/issues/65)

- [x] [Iphone S - Authentication by fingerprint causes layout and performance issues. #46
](https://github.com/threefoldtech/3Bot_connect/issues/46)

- [x] [Scanning QR on wallet while having the keyboard open does not close the keyboard, after closing keyboard the QR scan fails. #42](https://github.com/threefoldtech/3Bot_connect/issues/42)

- [x] [When the 3bot app is backgrounded, other apps performance is impacted. #41](https://github.com/threefoldtech/3Bot_connect/issues/41)

- [x] [Possible to show a crash screen to any user by sending invalid websocket data. #26](https://github.com/threefoldtech/3Bot_connect/issues/26)
