### ISSUE TITLE
jsx 10.3 blocking bugs [development_hotfixes]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#535]
- [x] jsx insystem installation https://github.com/threefoldtech/jumpscaleX_core/issues/512
- [x] webinterface locations don't get created https://github.com/threefoldtech/jumpscaleX_core/issues/472
- [x] None object has no attribute lpush https://github.com/threefoldtech/jumpscaleX_core/issues/516
