### ISSUE TITLE
January bugs & issues part1

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#54]
- [x] [Add the design files of the tftshop to the github repo](https://github.com/threefoldfoundation/tftshop/issues/4) (2h)(https://github.com/threefoldfoundation/tfchain/issues/249)
- [x] [a consensus from August 30 2018 holds the wrong minting conditions](https://github.com/threefoldfoundation/tfchain/issues/258)
- [x] [seems like the latest code does not fork on testnet block 148123](https://github.com/threefoldfoundation/tfchain/issues/262)
