### ISSUE TITLE
3bot user should be able to run auto testing environment

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#543]
- [x] should be based on zeroCI 
- [x] make sure zeroCI is flexible enough
- [x] [make sure zeroCI is not using mongo for cloud offering](https://github.com/threefoldtech/zeroCI/issues/23)
- [x] [Use zos v2 k8s cluster to run testsuites](https://github.com/threefoldtech/zeroCI/issues/24) because of payment
- [x] [update git to be used with github and gitea](https://github.com/threefoldtech/zeroCI/issues/26)
- [x] [3bot connect support](https://github.com/threefoldtech/zeroCI/issues/37)
- [x] [initial config from frontend](https://github.com/threefoldtech/zeroCI/issues/35)
- [x] [repository config](https://github.com/threefoldtech/zeroCI/issues/34) environment variables
- [x] [add build trigger](https://github.com/threefoldtech/zeroCI/issues/31)
- [x] [add stream logs](https://github.com/threefoldtech/zeroCI/issues/38)
- [x] [add auto update status](https://github.com/threefoldtech/zeroCI/issues/39)
- [x] [create docker image with zeroCI](https://github.com/threefoldtech/zeroCI/issues/25)
- [x] [more validation on initial config](https://github.com/threefoldtech/zeroCI/issues/45)
- [x] [periodic cleanup](https://github.com/threefoldtech/zeroCI/issues/43)
- [x] [yaml file validation](https://github.com/threefoldtech/zeroCI/issues/44)
- [ ] support for crystaltools (crystaldo = ct)
- [x] support for neph, see logs in the CI tool
edit: more tbd
