### ISSUE TITLE
distributed software engineering environment for 3bot users

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#545]
3bot user should be able to 

- [x] host their private git repos #544 
- [x] develop in online IDE #538 
- [x] have CI/CD #543

**Comment by xmonader** [comment]
not part of 2.0.6, should be moved to next.
