### ISSUE TITLE
logs / alerts fixes [development_logalert2]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/home#551]
**Related issues**

- [x] find logs inside filesystem not only redis : https://github.com/threefoldtech/jumpscaleX_core/issues/556
- [x] add an option to list current apps: https://github.com/threefoldtech/jumpscaleX_core/issues/546
- [ ] alerta: make sure deduplication works https://github.com/threefoldtech/jumpscaleX_threebot/issues/386

**Comment by rkhamis** [comment]
Already handled in webix for the admin dashboard
