### ISSUE TITLE
Ethereum erc-20 tft tokens and bridge

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#56]
Follow up story from #31 
A lot of the bigger exchanges support erc20 tokens but it would require some effort to support tftokens directly. By creating an erc20 token to represent tft, these exchanges can support an and transfer tft amongst each other without any effort.
We propose to be able to send tft to an ethereum address, the bridge would create the tfterc20's and add them to the target ethereum address. Maybe multisign is required to secure this.
The reverse depends if we can encode a tft adress in an eth adress, if not, a receiving adress needs to be published on the tft chain first. A user can withdraw from an exchange to an eth adress generated by a tft wallet and a blockcreator node would include the coin creation transaction to a block. Every full node can run a validator to only accept valid eth to tft transactions.
This would allow user to easily convert tft to tft erc20 and back, making the process to transfer tft to an exchange that supports tfterc20 and back almost seamless

![img_20181116_115333](https://user-images.githubusercontent.com/22023708/48617721-84ac0680-e997-11e8-8449-5339bb28f125.jpg)

Tasks:
- [x] [Basic erc20 contract and proxy contract](https://github.com/threefoldfoundation/tfchain/issues/223).Todo: 6h (@leesmet)
  - [x] [Research how to set up an ERC20 proxy contract](https://github.com/threefoldfoundation/tfchain/issues/221)
  - [x] [Document deployment and setup](https://github.com/threefoldfoundation/tfchain/issues/236)
  - [x] [Implement ownership](https://github.com/threefoldfoundation/tfchain/issues/235)
  - [x] [Eternal Storage to allow storage upgrades](https://github.com/threefoldfoundation/tfchain/issues/240)
  - [x] [erc20 contract upgrade logic is not upgradeable](https://github.com/threefoldfoundation/tfchain/issues/240)  Rob: Added a remark in the issue for the current solution, not urgent
 - Registration of a eth withdrawal address  in the tfchain
   withdrawal adress : blake2b ( tft adress) -> ( last 20 bytes) 
      - [x] [New transaction type](https://github.com/threefoldfoundation/tfchain/issues/217) (4h) (@GlenDC)
     - [x] document erc20 address registration tx
- [x] Oracle  service listens on these transactions and after a delay of 6 blocks, register  withdrawal address in  the eth contract (16h)
    - [x] Register withdrawel address method in ETH contract
    - [x] if balance on there, withdraw
    - [x] clean up bridge code 
    - [x] 6 block delay before calling the contract 
- New transaction type to send tft to an ethereum address
    - [x] [Implement this Tx and support this tx in tfchainc devnet](
https://github.com/threefoldfoundation/tfchain/issues/218)
    - [x] Document this Tx Type
    - [x] [query the status of a erc20 withdrawal address registration through the explorer](https://github.com/threefoldfoundation/tfchain/issues/248) 
- [x] Oracle  service listens on these transactions and after a delay of 6 blocks, creates new erc20 tokens (16h)
   - [x] [Basic bridge daemon that listens to the consensus set](https://github.com/threefoldfoundation/tfchain/issues/225)
  - [x] [Make the erc20 bridge wait 6 blocks before creating erc20 tokens](https://github.com/threefoldfoundation/tfchain/issues/229) 
- [x]  Newcoins method in the eth contract (6h)
  - [x] [Basic mint function](https://github.com/threefoldfoundation/tfchain/issues/230)
   - [x] only callable  by oracles 
   - [x] prevent double registration by including the transaction id
 - [x] transfer to a registered withdrawal address in the eth-contract
  - submit withdrawal event
  - burn erc20 tokens
- Support ERC20 Coin Creation Tx (used to create the TFTs exchanged back from the ERC20-funds, after these are burned on the ETH side of the action)
    - [x] Add and document [(tfchain) transaction to exchange ERC20-funds to TFT](https://github.com/threefoldfoundation/tfchain/issues/234)
    - [x] [validate that an ERC20 TxID can only be used once to fund an ERC20CoinCreationTx](https://github.com/threefoldfoundation/tfchain/issues/239) (3h)
   - [x] [define who/how one can create coins using the ERC20CoinCreationTransaction](https://github.com/threefoldfoundation/tfchain/issues/238)
- [x] Oracle service listens on these events and calls a create token transaction in tfchain including the eth transaction id (after a delay of 6 block confirmations) (8h)
  - [x] [6 block delay](https://github.com/threefoldfoundation/tfchain/issues/246)
- [x] [Validator module to be included in the blockcreators (or anyone else wanting to validate)
    checks the coincreation transactions and validates the transactions on the ethereum chain](https://github.com/threefoldfoundation/tfchain/issues/224) (2w)
   - [x] add the opt-in full ERC20 Tx validation to tfchaind, using a thin client connect to the Infura network
   - ~provide LES/v2 ((light) client) support for the GetTxStatus~ (No longer required, instead we have now also access to the BlockID in the CoinCreation Tx)
   - [x] modify the validator code to make use of a light (eth) client instead of doing it as a thin (eth) client
   - [x] [ensure tfchaind is fully synced with the ETH network prior to starting](https://github.com/threefoldfoundation/tfchain/issues/247)
 - [x] [eth and tfchain data is written in different locations](https://github.com/threefoldfoundation/tfchain/issues/233)
- [x] [Add ropsten and main ethereum networks to the er20 bridge](https://github.com/threefoldfoundation/tfchain/issues/232)
- [x] [prevent double calls to registering address and convert transaction](https://github.com/threefoldfoundation/tfchain/issues/253)
- [x] [Find out why bridge calls fail with insufficient gas](https://github.com/threefoldfoundation/tfchain/issues/252)
- increase and enforce block delay
    - [x] [Increase block wait timeout to 30 blocks](https://github.com/threefoldfoundation/tfchain/issues/263)
    - [x] [Ensure ERC20 validator enforces 25 confirmations prior to accepting a ERC20 CC](https://github.com/threefoldfoundation/tfchain/issues/265)
- [x] [Require a minimum amount for withdrawing](https://github.com/threefoldfoundation/tfchain/issues/264)
- [x] [Remove BridgeFee from ERC20 CoinCreation Transaction](https://github.com/threefoldfoundation/tfchain/issues/266)
- [x] [Consensus checksum mismatch](https://github.com/threefoldfoundation/tfchain/issues/271)
(https://github.com/threefoldfoundation/tfchain/issues/273)
- [x] [Support Relevant ERC20 Transactions in JumpScale Libs](https://github.com/threefoldtech/jumpscale_lib/issues/273) (2d)
- [x] verify that the JS client is fully compatible with the ERC20/3Bot Txs/features as will be used in the `1.1.2-rc1` release;

The reason  for the registration of withdrawal adresses is than an ethereum adress is just 20 bytes, the contract would not be able to see the difference between a transfer and a withdrawal if withdrawing from an exchange without this. 
Also, there is no free choice of ethereum address  since it would be possible to steal someone else's token otherwise and requiring an ethereum private key and signature would only complicate things a lot.

**Comment by GlenDC** [comment]
@robvanmieghem and @LeeSmet, I don't think we defined yet how the oracle will register and create the new coins that were created using transferred ERC20 tokens, did we? I assume it doesn't use the CoinCreation Tx's. Yet it does require powers to create tokens somehow? Either I missed something or that part still has to be defined.

**Comment by LeeSmet** [comment]
I thought we said that a new transaction type would be created when converting back from ERC20 to TFT, with a field which contains the txID of the transaction on the ethereum chain that was used for the withdrawal/burn

**Comment by GlenDC** [comment]
Sure but that does mean that the bridge somehow need to have powers defined to create coins, using this new Transaction Type. Making the bridge even more of a weak point, given an attacker could use it to give coins to themselves once in control of the bridge.

**Comment by LeeSmet** [comment]
I'm not really sure that this *NEEDS* to be done by the bridge. After all, if we have a txID on the ether chain, the block creators can just just check said transaction through an ethereum explorer (or local ETH node) to verify if the right amount of coins is created, and to ensure that the tx is not a duplicate. Ofcourse we could do the same trick as with the coin creation where we have a special multisig with oracle keys saying at least e.g. 3 out of 5 must sign

**Comment by LeeSmet** [comment]
Flow is working currently against the rinkeby proxy/token contract from a local devnet. Ignore the conversion between erc20 and tft tokens, it is currently (very) wrong.

# Sending tokens from tfchain to ERC20

## Tfchain transaction

![image](https://user-images.githubusercontent.com/22023708/50285161-a9ded980-045b-11e9-9f9e-e53272588a9b.png)

## Rinkeby transaction

https://rinkeby.etherscan.io/tx/0x18d54f3a4a0853adb06a8255a5ec0fbbaa4f6af36dc707739e00fff0c6c5b924

# Registering ERC20 withdrawal address

## Tfchain transaction

![image](https://user-images.githubusercontent.com/22023708/50285485-9a13c500-045c-11e9-8fef-4552cac39a27.png)

## Rinkeby transaction

https://rinkeby.etherscan.io/tx/0xb12e582aa0801c8d55e1cebaefa670c8097be63c76f9cd702b3a6d1eb39602b3

# Sending tokens from ERC20 to Tfchain

## Tfchain transaction

![image](https://user-images.githubusercontent.com/22023708/50285747-7604b380-045d-11e9-8792-155a0ed69a7e.png)

## Rinkeby transaction

https://rinkeby.etherscan.io/tx/0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8

**Comment by GlenDC** [comment]
> https://rinkeby.etherscan.io/tx/0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8

Is it normal that I see the following error on that page:

<img width="815" alt="screen shot 2018-12-20 at 17 57 02" src="https://user-images.githubusercontent.com/3900482/50298976-bfb2c580-0480-11e9-9e7c-1c538b038bd5.png">

**Comment by GlenDC** [comment]
@LeeSmet, didn't you already finish

```
Oracle service listens on these events and calls a create token transaction in tfchain including the eth transaction id (after a delay of 6 block confirmations) (8h)
```
? Doesn't seems to be checked off yet, but I can swear that you are already doing that.

**Comment by LeeSmet** [comment]
> > https://rinkeby.etherscan.io/tx/0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8
> 
> Is it normal that I see the following error on that page:
> 
> <img alt="screen shot 2018-12-20 at 17 57 02" width="815" src="https://user-images.githubusercontent.com/3900482/50298976-bfb2c580-0480-11e9-9e7c-1c538b038bd5.png">
> 
> **EDIT** I suppose it is a harmless etherscan error, as the Tx does look valid on the chain and I can decode the data and even validate that it is as expected, so probably can be ignored.

I am assuming this has to do with the fact that it is not an ERC20 transfer, but rather a withdrawal. Since that event has a slightly different layotut, the web ui of etherscan likely just can't decode it

**Comment by robvanmieghem** [comment]
same with the deployment:https://github.com/threefoldtech/home/issues/89
