### ISSUE TITLE
IT Env Bootstrap [development]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#571]
Team:  @xmonader, @despiegk, @m-motawea, @hossnys, @PeterNashaat 

## Phase 1

- [ ] JSX unstable branch digital ocean machine 2GB (Amsterdam)
- [ ] Everyone has login as supposed to be: despiegk, … (7letter max lastname)+1 letter first name
- [ ] Everyone has ssh login onto the machine /home/$loginname
- [ ] Push with syncer from your own machine 
- [ ] Use builder to install [gitea](https://github.com/threefoldtech/jumpscaleX_builders/issues/57) (for later)
data for gitea in /itdata/gitea
- [ ] Use builder to install [syncthing](https://github.com/threefoldtech/jumpscaleX_builders/issues/58)
- [ ] Make users on gitea (loginname)
- [ ] Enable UFW: only ssh & 443

## Phase 2
threefold/itenv_core  will be our core itvenv for this bootstrap environment.
Script the following
- [ ] Deploying 3 digital ocean machines (first one specs is above), in 3 chosen locations
- [ ] [Syncthing](https://github.com/threefoldtech/jumpscaleX_builders/issues/58) syncs /itdata to 3 machines
- [ ] Gitea is only on the first machine, but because of the syncthing the git repo’s are synced
- [ ] Gateway (coredns, tcprouter, redis master on machine 1) 
- [ ] Wireguard network to first machine (check jsx connect with kristof)

to be delivered within 1 month
