### ISSUE TITLE
make sure all is working for our first grid launch in April 29

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#599]
see https://circles.threefold.me/project/sacha96-threefold-marketing/us/556?kanban-status=92

TFTA creation ongoing : 
- [x] [Modify conversion service](https://github.com/threefoldfoundation/tft-stellar/issues/107)
- [x] [Create TFTA issuers](https://github.com/threefoldfoundation/tft-stellar/issues/105)
- [x] [Bypass sms service for now](https://github.com/threefoldfoundation/tft-stellar/issues/102)
- [x] [Deploy to production](https://github.com/threefoldfoundation/tft-stellar/issues/113)

**Comment by gmachtel** [comment]
Testing payment integration behind schedule, plus TFTA definition blocking the go-live of 3Bot connect app. See https://circles.threefold.me/project/despiegk-tftech-software/kanban?kanban-status=404
