### ISSUE TITLE
fixes stabilize 10.4 [unstable_fix1]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#612]
today we want to be done with stabilizing 10.4 to track progress about minor fixes, this story
so we can do pull requests over the day

- [x] codeserver install  threefoldtech/jumpscaleX_threebot#485
- [x] admin: when error e.g. in installing package there was no alert or even logs threefoldtech/jumpscaleX_threebot#487
- [x] admin: delete alert does not work threefoldtech/jumpscaleX_threebot#488
- [x] packages cleanup in 3bot threefoldtech/jumpscaleX_threebot#489
- [x] solutions not working in admin, none of them
- [x] codeserver did not install, yet it says its running threefoldtech/jumpscaleX_threebot#491
- [x] update package simulator threefoldtech/jumpscaleX_threebot#490
- [x] review package manager threefoldtech/jumpscaleX_threebot#498

**Comment by waleedhammam** [comment]
solutions not working in admin, none of them: Pull weblibs

**Comment by waleedhammam** [comment]
Fixed alerta actor: https://github.com/threefoldtech/jumpscaleX_threebot/commit/2dc69f203db9cdc457a738b5039e2b601c9551d9

**Comment by waleedhammam** [comment]
packagemanager: https://github.com/threefoldtech/jumpscaleX_threebot/issues/498
