### ISSUE TITLE
JSX work review [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#621]
# admin/3bot 
- [x] [memory usage in dashboard is misleading, is it in the right scale?](https://github.com/threefoldtech/jumpscaleX_threebot/issues/513)
- [x] [4 codeservers process when it starts investigate why?](https://github.com/threefoldtech/jumpscaleX_threebot/issues/514)
- [x] [jupyter start not working smoothly, should be < 10 sec](threefoldtech/jumpscaleX_threebot#515)
- [x] [2 simulators (simulator, tf_simulator -this one is the play-)  (change name)](https://github.com/threefoldtech/jumpscaleX_threebot/issues/516)
- [x] [new: jupyter package for the grid, separate package ](https://github.com/threefoldtech/jumpscaleX_threebot/issues/518) (check with @weynandkuijpers )
- [x] [faucet package for tft](https://github.com/threefoldtech/jumpscaleX_threebot/issues/517) (check with @robvanmieghem)
- [x] [don't show health check for codeserver/jupyter if not installed](https://github.com/threefoldtech/jumpscaleX_threebot/issues/531) 

# chatflows
- [x] [ask expiration for each solution deployed](https://github.com/threefoldtech/jumpscaleX_threebot/issues/519)
- [x] [check existing network, was not working](https://github.com/threefoldtech/jumpscaleX_threebot/issues/523)
- [x] [check if flist exists before using in chatflow](https://github.com/threefoldtech/jumpscaleX_threebot/issues/521)
- [x] [don't allow 'seq' choice in S3](https://github.com/threefoldtech/jumpscaleX_threebot/issues/520)
- [x] [don't use words data/parity, use (nr of locations, locations allowed to fail) and default 6+3 if not sure](https://github.com/threefoldtech/jumpscaleX_threebot/issues/522)
- [x] [use SSH key for the ubuntu & flist solution] (should be in 10.5) (https://github.com/threefoldtech/jumpscaleX_threebot/issues/524)
- [x] disable QR Code/escrow details screens
- [x] [make sure nodes aren't repeated in network reservations in chatflow](https://github.com/threefoldtech/jumpscaleX_libs/issues/147)

# infra
- [x] [play.grid.tf](https://docs.grid.tf/christophe/itenv_tfgrid#simulator-playground): and we don't pull, pulling can implemented.

- NEXT WEEK: security on webgateway
