### ISSUE TITLE
explorer payment flow improvements

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#622]
Track all the improvement we want to bring to the payment flow handled by the explorer

-  [x] [avoid generating currency account on behalf of users](https://github.com/threefoldtech/zos/issues/666)
- [x] [allow farmer to mark some node as free to use](https://github.com/threefoldtech/zos/issues/667)
- [x] [review resource price definition and management](https://github.com/threefoldtech/zos/issues/668)
- ~~[ ] investigate conversion from TFTA to TFT (cc @robvanmieghem)~~ moved to https://github.com/threefoldtech/home/issues/655

**Comment by zaibon** [comment]
@robvanmieghem can you write down a couple of line to explain exactly how the conversion from TFTA to TFT needs to happens. Specially I'm interested in how do we need to handle TFTA in the reservation payment flow.
