### ISSUE TITLE
solutions improvements [unstable_solutions]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#623]
- [x] [ask name for each solution deployed](https://github.com/threefoldtech/jumpscaleX_threebot/issues/528)
- [x] [list solutions deployed to allow deletion](https://github.com/threefoldtech/jumpscaleX_threebot/issues/529)
- [x] [ssh authorization for ubuntu/flist](https://github.com/threefoldtech/jumpscaleX_threebot/issues/524)
