### ISSUE TITLE
Digital Me Components Cleanup pt 2

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#63]
Each component in Digital Me needs to be working, clean and documented on its own.
In this story card, these components will be tracked:

- [ ] parent of https://github.com/threefoldtech/digital_me/issues/72 Web frontend cleanup
- [x] parent of https://github.com/threefoldtech/digital_me/issues/73 Chatbot cleanup
- [ ] parent of https://github.com/threefoldtech/digital_me/issues/74 Packages cleanup

**Comment by rkhamis** [comment]
This storycard is no longer relevant. Will close
