### ISSUE TITLE
generic checklist for 10.5

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#632]
## new is

- [x] support for free TFT  
- [x] payment integration(Jo/Rana)
- [x] the admin improvements ([see here](https://github.com/threefoldtech/jumpscaleX_threebot/issues/563))
- [x] when using wizards chose on which farmer and/or node for single-node solutions
- [ ] ~~gateway integration~~
