### ISSUE TITLE
10.4 finishing checklist [unstable]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#633]
- [x] more testing & better documentation around the 5 primitives : 
    - [x] much more testing
    - [x] more hardware deployed
- [x] [admin:selection in admin panel somewhere between testnet/production net](https://github.com/threefoldtech/jumpscaleX_threebot/issues/570)
- [x] [admin: a page which shows the capacity of grid (can be iframe for other website)](https://github.com/threefoldtech/jumpscaleX_threebot/issues/569) take into consideration testnet/production
- [x] [admin: integrate tfwikis in dashboard](https://github.com/threefoldtech/jumpscaleX_threebot/issues/576)
- [x] [admin: the wikis in 3bot](https://github.com/threefoldtech/jumpscaleX_threebot/issues/553)
- [x] [chatflows: Show on screen and save data in bcdb for later reference.](https://github.com/threefoldtech/jumpscaleX_threebot/issues/571)
- [x] [chatflows: improvement wizard webgw (without below its not a minimum viable product)](https://github.com/threefoldtech/jumpscaleX_threebot/issues/572)
- [x] kubernetes [docs](https://github.com/threefoldtech/zos/tree/master/docs/kubernetes#connect-to-the-cluster) in chatflow docs threefoldtech/jumpscaleX_threebot#574
- [x] [new build needed of container](https://github.com/threefoldtech/jumpscaleX_core/issues/735)
    - [x] codeserver as binary already in image
    - [x] but zerotier in, see docker installtools has code how to use zerotier
- [x] simulator needs to be upgraded (kristof)
- [x] 3sdk
     - [x] [the 3sdk needs to be documented](https://github.com/threefoldtech/jumpscaleX_core/issues/719) (expert and not mode) in relation to identity as documented in core docs in jumpscale as well
     - [there are TODO in 3sdk, mainly connecting methods to existing functionality] (https://github.com/threefoldtech/jumpscaleX_core/issues/743) (moved to 10.5)
     - [x] [support for windows](https://github.com/threefoldtech/jumpscaleX_core/issues/722)

when done 
- [x] code on development branch & tag set
