### ISSUE TITLE
sdk migration to js-ng

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#671]
[js-ng](https://js-next.github.io/js-ng/wiki/#/) is approved to replace the current JSX and to complete that migration we need to list the current things that need to be resolved/ported in js-ng 

- [x] [aligned encryption mecahnism with j.me](https://github.com/js-next/js-ng/issues/237)
- [x] chatflow engine (with state mgmt) not merged yet in jsx (https://github.com/threefoldtech/jumpscaleX_threebot/pull/663)
- [x] [executors](https://js-next.github.io/js-ng/wiki/#/./executors)
- [x] threebot
  - [x] [core](https://js-next.github.io/js-ng/wiki/#/./rpc)
  - [x] auth
  - [x] http support(Only allow requests through a session)
  - [x] packages
- [x] [sal ZOS/Stellar client](https://github.com/js-next/js-ng/issues/246)
- [x] [schemac](https://github.com/js-next/js-ng/issues/244) to compile existing schemas in jsx
  - [x] [dependecy resolver](https://github.com/js-next/js-ng/blob/wip_zossal/jumpscale/tools/depsresolver/depsresolver.py) 
- [x] [admin panel](https://github.com/threefoldtech/js-sdk/issues/2)
- [x] Nginx sal
- [x] [solutions](https://github.com/js-next/js-sdk/issues/4)
- [x] development installer using pip, virtenv... how we do it today & brew on osx, apt on linux

## implementation requirements

- [x] config mgmt data store = filesystem + sqlite for index (if already needed): we have alternativ backend but indexing we didn't hit so far.
- [x] don't need docker on desktop for using 3sdk (already works on host without problems) if deps available
- [x] only external server components needed = redis & nginx (run in tmux using ct tool)

**Comment by xmonader** [comment]
- images already gets created on every push https://github.com/threefoldtech/js-ng/blob/development/.github/workflows/build_image.yml and tagged images too https://github.com/threefoldtech/js-ng/blob/development/.github/workflows/build_tagged_image.yml, probably will need to update the github action to push to the playground. going to be tracked here https://github.com/threefoldtech/js-ng/issues/335

- bundling crystal tooling related can't be addressed atm
  - we just released a crystal tools version.
  - new crystal version with breaking api leading to undefined beahvior
  - windows support
  - the tooling already existing in js-ng and adds more complexity to handle both right now

**Comment by sasha-astiadi** [comment]
@xmonader @rkhamis can we close this?
