### ISSUE TITLE
TFGrid S3 = storage project phase 2 (Hercules)

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#720]
[Hercule storage solution](https://docs.google.com/document/d/1HzyElPiy3NTELSiYvAaJ47tMAr0-smBjbdJNcASJ5KU/edit#heading=h.ktkmsaklxsca)

Following https://github.com/threefoldtech/home/issues/568 this phase will fill the gabs in the documentation of the Hercule storage solution as well as allow self-healing to be implemented by the users.

## Tasks
- [x] rebase minio on upstream
- [x] document solution
  - [x] diagram of the solution
  - [x] data flows
  - [x] disaster recovery
  - [x] How to deploy master/slave setup
  - [x] [add an endpoint that is available on slave to switch to master mode](https://github.com/threefoldtech/minio/issues/101)
  - [x] Capacity requirements. CPU and memory of the minio contanier but also how much local disk storage is required for the metadata. User should be able to know how much metadata storage is requires based on it's archive size
- [x] Monitoring should expose solution health.
  - [x] health of each shards
  - [x] storage used/free for data and metadata
  - [x] implement healing API client
  - [x] Grafana dashboard
  - [x] Complete tutorial on how to deploy a archive solution with monitoring and example self-healing 
  - [x] [make sure all 0-DB deployed on the grid are running latest version that includes](https://github.com/threefoldtech/zos/issues/799): https://github.com/threefoldtech/0-db/commit/b5155357d5a4c76fb68480f2b1cc1931f7041291
scripts
- [x] Research around how to allow a user to trigger healing of the shards.
- [x] Add chatflow and/or example script how to deploy monitoring solution
  - [x] Make sure flist for prometheus, grafana with ssh enabled

**Comment by muhamadazmy** [comment]
## Minio
- Minio allows only the admin API for healing if running in server mode `minio server`. I did some research and dropped a question on slack and this was confirmed.
- To kick start healing on minio, may be it's better if we include a tiny API process in the official minio container that we can control with simple request to start healing, either directly via the 0-store client or by starting the special gateway command we added to minio that only does healing.

## Prometheus 
- Prometheus management API doesn't expose endpoints to configure Prometheus unfortunately,  so to have an automated installer for prometheus we have 2 options:
- Make sure we install the system that need to be monitored first, collect all it's information and then deploy prometheus pre-configured:
  - either by merging config into the flist
  - or by env variables (will require a custom endpoint, to handle the env and build the proper config
- Or, include another process in the prometheus container that we can call remotely to configure and reload prometheus

**Comment by zaibon** [comment]
All your remark regarding prometheus are not really our concerned. The way how users configure their monitoring solution if their own problem.  Our focus is just to make sure all the required variable needed to implement healing decision are available on minio.

**Comment by muhamadazmy** [comment]
@zaibon that was regarding the last check box on the list! if we don't care about prometheus setup, this check box should be removed then.

**Comment by hteibler** [comment]
is this also related to:
https://github.com/threefoldtech/home/issues/734

**Comment by hteibler** [comment]
and can you add SSH access to the container

**Comment by zaibon** [comment]
> is this also related to:
#734

yes, we are adding more information regarding the shards status and health of the storage system.

**Comment by muhamadazmy** [comment]
Update: chat flow for installing minio already exists [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py)

**Comment by zaibon** [comment]
> Update: chat flow for installing minio already exists here

Can we deploy the monitoring that goes with the archive through the chat bot ?

**Comment by muhamadazmy** [comment]
Prometheus chatflow: https://github.com/threefoldtech/jumpscaleX_threebot/issues/744

**Comment by muhamadazmy** [comment]
Docs: https://github.com/threefoldfoundation/info_tfgridsdk/blob/561386a9e4ec215354e368c559c70d028d722eff/src/6_develop/storage/tutorial.md
