### ISSUE TITLE
Decouple payment of capacity from reservation deployment

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#749]
We have received quite some request for a feature that allow to "update" a workloads once it has been deployed. The main complain was that once a reservation is payed for there is no way to change it and cancelling it make you "loose" the token paid.

As a solution a new specification regarding capacity payment and deployment has been started.
**Specificattion**: https://github.com/threefoldtech/tfexplorer/blob/master/specs/modify_IT_contract_over_time.md. 
The output of this exercise is a system where the payment of capacity is decoupled from the deployment of workloads.  

With this system in place, a user just have to reserve capacity once and he can deploy/cancel any workloads without any additional charges.

## Tasks 
- [x] Cleanup and merge specification : https://github.com/threefoldtech/tfexplorer/pull/64
- [x] Implement a concept of a capacity pool in the explorer
- [x] Abitlity to set a pool on a workload
- [x] Rework and remove reservation, so workloads become stand-alone
- [x] Rework network primitive, so individual network resources become the workloads
- [x] [Update JSX python client and SAL](https://github.com/threefoldtech/jumpscaleX_libs/issues/239)
- [x]  [refactor chat flow once client and SAL is updated](https://github.com/threefoldtech/home/issues/841)
- [x] [Update tfexplorer to support capacity pool](https://github.com/threefoldtech/tfexplorer/pull/115)
- [x] [Implement migration for existing workloads](https://github.com/threefoldtech/tfexplorer/pull/115))
- [x] [Update 0-OS to support new workloads](https://github.com/threefoldtech/zos/pull/858)

## Bugs
- [x] https://github.com/threefoldtech/tfexplorer/issues/129
- [x] https://github.com/threefoldtech/tfexplorer/issues/135
- [x] https://github.com/threefoldtech/tfexplorer/issues/136
- [x] https://github.com/threefoldtech/tfexplorer/issues/144
- [x] https://github.com/threefoldtech/zos/issues/887

**Comment by LeeSmet** [comment]
Some things which we still need to resolve:

- A pool is paid for until it expires. This means that a client who does not utilize its full pool 100% of the time effectively pays more. If a deployment fails after some time, then there is no longer a refund, but the pool is unusable during this time
- While a pool can be extended in time, it might also be interesting to allow it to be increased/decreased in size when it is extended. Decrease because you might want to remove some workloads. Increase could be handled by adding another pool, if this is flexible enough so that we don't have any spare resources going to waste.
- Building on the previous point, if we do allow decreasing the size of the pool, and there are more resources used by the provisioned workloads than the size of the decreased pool, how do we decide what workload to elminate.

**Comment by zaibon** [comment]
> If a deployment fails after some time, then there is no longer a refund, but the pool is unusable during this time.

What do you mean by the pool is unusable ?

> While a pool can be extended in time, it might also be interesting to allow it to be increased/decreased in size when it is extended.

Indeed that is the idea. increase the size of the pool should be doable at anytime as long as the farm as enough capacity. Shrinking should only be allowed if the new size is not smaller then the total of resource units currently used by all the workloads

**Comment by DylanVerstraete** [comment]
In order to move forward on this we need atleast following things:

In zos:
- [ ] create a new type definition of the Pool object
- [ ] link the provisioning of a workload to a Pool

In the explorer:
- [ ] create new endpoints to manage Pools and make Pool reservations.
  - [ ] create a pool
  - [ ] edit a pool
  - [ ] list available pools
  - [ ] ...
- [ ] refactor the escrow code to manage Pools instead of workloads.
- [ ]

**Comment by zaibon** [comment]
> In zos we don't want to touch the code and let the explorer handle most.

So 0-OS will still received the exact same type of reservation ? What about expiration time ? 0-OS should do a check against the explorer to make sure the pool the reservation is linked too is still valid no ?

>  extend existing primitives to have a link to a Pool

Are we going to allow linking different pool form the same reservation ? So we link workloads to a pool or the full reservation ?


Also, regarding compatibility I don't think we can afford breaking the API completely. We need to give time to people to adapt to the new model. So is it possible to keep the current reservation flow in place and add the capacity pool next to it? we would run this for a while until deprecating the current reservation flow?

**Comment by DylanVerstraete** [comment]
> What about expiration time

We can treat expiration times when it's linked to the new reservation type as deprecated and ignore that?

> Are we going to allow linking different pool form the same reservation ? So we link workloads to a pool or the full reservation ?

I think we should link workloads to pools

We can keep being compatible if we process reservation of the new type with the new logic, if it's a reservation with workloads and expiration dates we process it as we do now.

**Comment by LeeSmet** [comment]
I think its best if we keep all the logic regarding the pool in the explorer. From the point of view of the node, the pool is an abstract concept anyway. As said in the specs, the farmer should eventually decide what to do with a reservation, which happens on a layer above the node. Imo, a node should only care about deploying actual, real, workloads, as instrumented by the farmer (or its replacement).

Furthermore, by keeping the logic out of the node itself, we allow maximum customization of the decision logic for the farmer once the farmer bot is here, with the implementation that will be created here as a sane default.

Ultimately, this could be implemented as a backward compatible change w.r.t the node. We add a field on the reservation workload which links to an available capacity pool. The node itself does not care for this. New workloads can then set their expiration to a really long time (or leave this out, or a version field)... In the explorer, we issue delete commands to workloads if their associated pool expires. This allows both types of reservation on the node at least. 

We will need to link the workload to a pool rather than the reservation. Reason being that a pool is tied to a node, and a reservation can deploy workloads on multiple nodes. Allowing multi-node pools is an issue because then it is not clear how much capacity should be reserved per node.

By creating a pool reservation, we can slot into the existing reservation system, in this regard, a pool reservation would be a new primitive. It would also be the only one which requires the escrow from now on. And since we use the existing reservation, we can operate both the new and the old model at the same time: the pool becomes a standalone object, and a workload reservation can either link a pool to deploy from (making it "free", as it is already paid for), or it does not link a pool, meaning its an old style reservation, which does need to be paid before it is deployed. This should allow us to operate both systems at the same time, without too much changes to the explorer codebase I think. Tooling can then be pushed towards creating reservations based on pools, so we can eventually drop support for old style reservations. Or we keep them, if that is eventually desired

**Comment by zaibon** [comment]
@LeeSmet I pretty much agree with everything you said. I was seeing the same way. 
My only concerned is the one node per pool. I don't see how this can work. This would requires to created so much pools... To me a pool was just a bunch of resource units you buy from a farm or a list of nodes. And then you can deploy on any of those nodes. It makes the capacity planning a bit more complex to do but like you said, ultimately its up to the farmer to decide how we wants to process the reservations

**Comment by DylanVerstraete** [comment]
> My only concerned is the one node per pool. I don't see how this can work. This would requires to created so much pools...

I have the same concern. As I see it a capacity pool is a pool of nodes on which you can deploy stuff. After the user has setup such capacity pool, he can use the old style reservation where he can select a node by id and add the reservation pool ID to it.

For example: 
A user makes a pool with 1 Gb storage and select 3 nodes for it. He pays for his pool and it gets actived.
Next he deploys something that needs 500 mb on node X (which is in his pool), we allocate these resources on the node at execution time and deploy his workload.
After the workload is deployed, 500 mb will still be available in his pool.

**Comment by joefoxton** [comment]
Hey Guys, great to see this conversation happening. Please have a read of #790. Maybe I can add some helpful colour/thoughts...

We've done deep research into the traditional, non blockchain market and have found that there is no appetite for pre-paying for capacity unless there are steep discounts. The market demands pay-as-you-go in fiat. This can either be achieved at the Jumpscale level, or at the farmer level. We are taking responsibility and currently working on the latter, ie...

1. The customer requests S3/K8s tenants, entering their fiat payment details. We ask them to estimate their monthly usage.
2. We reserve capacity on their behalf using an "agent" threebot, and our own TFT. We reserve based on their monthly usage estimates, with some headroom.
3. We hand the customers their tenant access key and secret key, then discard them to retain our customer's privacy. They can now access and manage their capacity using their min.io client or K8s client libraries.
4. Every month we look at their actual usage metrics (not yet available, as per #790) to bill them in fiat.

Never do we need to convert their fiat to TFT. Never does the customer have to worry about crypto.. until they are ready to.

This is quite a risky model, but the only model we see working in the short term given the market's demands. We are willing to take this risk and try to make the model work. Indeed, we think we can win some of the market with transparent fixed fiat pricing, but only if we can prove in the coming months that we can manage cost.

However, we'd embrace a pay-as-you-go, usage-based billing model at the threefold level, rather than a fixed reservation-based model that requires an untenable level of risk on the customer's side.

At the end of the day our goal is to validate the grid, therefore lifting the TFT price, and moving the ball forward towards a decentralised future. First we need to convince early adopts and then mainstream that we can build a sustainable infrastructure operation. First things first.

**Comment by zaibon** [comment]
Testnet has been upgraded to support the new capacity pool system.

**Comment by Dina-Abd-Elrahman** [comment]
- I tested a capacity pool on JSX with all solutions, there was a bug in solutions and it has been fixed.

Commit_ID:2841e1109abf1bee113b027a7e04bfbd25cbcb48
