### ISSUE TITLE
crystaldo

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#754]
- work with Kristof on it

## todo phase 1

- [x] ssh connection using the config format (as part of crystal do cmdline, start ssh) to be used as subcommand
- [x] test/fix tmux functionality
- [x] test/fix git functionality
- [x] logging on or off using a env variable ```export DEBUG = 1```
- [x] execution issue (have execution with pipe's) https://github.com/threefoldtech/home/issues/709
- [x] ssh executor
  - [x] check ssh libs, check agent support
  - [x] connect using agent
  - [x]  upload
  - [x] download
  - [x] execute
  - [x] shell
 
- [x] neph
  - [x] fire parallel jobs in using `crystaldo tmux run` by describing them in the yaml input file for neph
  - [x] when you receive a webhook for a specific repo, you go to repo/deployment dir if it exists and if there's a neph.yaml file there we fire a neph in a tmux ( in case of multiple webhooks, we queue them)
 

## phase 2

- [x] remove code from publisher, ... which is in crystaltools, so we can use 1 codebase

**Comment by ashraffouda** [comment]
regarding ssh executor,
I found an issue in the ssh2 library on crystal fixed it and sent them a pr
it is almost done, now it is missing the shell thing
