### ISSUE TITLE
Monitoring solution for 0-OS workloads [development_monitoring_chatflow]

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/home#761]
Allow a user to deploy a monitoring solution that he can uses to watch it's workloads health.

Basic monitoring stack would be:
- prometheus as time serie database
- grafana for dashbaord
- redis as pub/sub logging service

Prometheus and grafana can just be deployed into containers, nothing special about it.
For the logging system, the 0-OS container allows to configure a redis endpoint where all the logs will be pushed using the pub/sub redis commands.

## Tasks
- [x] Chat flow to deploy monitoring solution
  - [x] promethus
  - [x] grafana
  - [x] redis server
- [x] Update chat flows to optionally configure container logs streaming
- [x] Update admin panel with page to see the grafana dashbaords

Example flow to deploy prometheus:
- Use this flist `https://hub.grid.tf/tf-official-apps/prometheus:latest.flist`
- Always as the user for his `ssh key`
  - The ssh key is passed to container as env variable `SSH_KEY=<input>` 
- Create an extra volume
  - Ask user for data volume size
- Volume is mounted in container under `/data`
- Use empty `entrypoint`

**Comment by grimpy** [comment]
@muhamadazmy @zaibon sounds good, do we already have a grafana flist somewhere?

Is the documention somewhere how to configure those apps to work together?

How does one configure a new container to log towards this system?

**Comment by zaibon** [comment]
> Is the documention somewhere how to configure those apps to work together?

I don't think we can auto configure prometheus out of the box when deploying. Instead these container should have ssh access to admin can update configuration and restart the processes when needed.

> How does one configure a new container to log towards this system?

@maxux is documenting it right now in the sdk.

**Comment by ranatrk** [comment]
Progress on new chatflow : https://github.com/threefoldtech/jumpscaleX_threebot/commit/570cee4447a7ac96e20c2e6065d46cef8a6aebf1
- Created overall structure of the monitoring solution chatflow
- included the items of the monitoring stack
- Prometheus deploys successfully

TODO: work on containers that will have grafana and redis running on them

@zaibon Is there an flist for grafana or should a new one be created?

**Comment by zaibon** [comment]
> @zaibon Is there an flist for grafana or should a new one be created?

I've no idea. But if you create one, have a look at what @muhamadazmy has put in place https://github.com/muhamadazmy/apps/tree/master/prometheus to build its images. So all images are consistent in the way they work.

**Comment by ranatrk** [comment]
Progress :  
https://github.com/threefoldtech/jumpscaleX_threebot/commit/1e27682df8c5feefc7756d1bf2802c78f7ab2a14
- Include grafana container, there was a working flist created so was directly used 
- Add logs for grafana and prometheus but stuck on log error 
    https://github.com/threefoldtech/tfexplorer/issues/106

**Comment by ranatrk** [comment]
@muhamadazmy @zaibon  Regarding the point `Update chat flows to optionally configure container logs streaming` do you believe the user should already have their redis setup and they enter the IP,Port...etc or should we setup and deploy a container with redis where we direct the logs to authomatically??

**Comment by Dina-Abd-Elrahman** [comment]
- verified
