### ISSUE TITLE
upgrade js-sdk with capacity pool feature [development_capacitypool]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#841]
We need to upgrade js-sdk chatflows to work with #749 

- [x] upgrade explorer client for workloads and pools
- [x] upgrade ZOS SAL
- [x] migrate new sals for deployer and solutions
- [x] network
- [x] ubuntu
- [x] genric flist
- [x] Minio/S3
- [x] K8S
- [x] Gitea
- [x] Domain delegation
- [x] Solution expose
- [x] 4To6 gateway
- [x] Monitoring
- [x] Pools
- [x] Threebot
- [x] Publisher
- [x] Upgrade dashboard (listing and cancelling solutions, add pools view)
- [x] Workload migration in dashboard
- [x] Verify gateway related solutions on testnet (4to6gw, expose, domain delegation, threebot, publisher)
- [x] Fix Threebot and solutions expose listings and add capacity to solution info
- [x] Handle multi-pool deployment in publisher and threebot (reserve domain in any pool with gateway available & reserve containers in any pool with resources available)

consult the upgrade in [jsx](https://github.com/threefoldtech/jumpscaleX_libs/pull/243) 

#### TODO:
create issues in js-sdk to reference here.

**Comment by Dina-Abd-Elrahman** [comment]
error in ubuntu solution 

https://github.com/threefoldtech/home/issues/865

**Comment by waleedhammam** [comment]
> error in ubuntu solution
> 
> #865

I think it's not related with this issue, it's completely different, it's for the flist itself

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
