### ISSUE TITLE
Improve the SDK/Farming setup user experience 

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#853]
This Story will serve to gather all UX feedback and issues/difficulties encountered when trying to setup the SDK and farm tokens. 
For actual bugs, necessary issues will be created in the repos.

- [ ] Information should be easier to find.
When googling how to become a farmer, the https://www.farmer.threefold.io/ page comes up, and is also frequently linked from the threefold website, however this page does not give you any info on how to become a farmer. Only the https://threefold.io/capacity.html seems to have a link to how to set up your own farm. Either all information should be more central or certain key information should be repeated in more places.

- [ ] SEO should be improved
The page I'm actually looking for is the how to setup your own 3SDK, however I can't seem to get there with many common google searches.
how to setup tft farm threefold
how to become an independent farmer threefold
how to farm your own TFT tokens
....

- [ ] DIY guide talks about migrations, even though it is what I was linked when trying to set up for the first time ever.
https://sdk.threefold.io/#/v2_jsx_farmsetup talks about a document that should be read and about migrations, this is very confusing to a new farmer and makes it seem like they are somehow on the wrong wiki page.
![image](https://user-images.githubusercontent.com/59569757/88153028-2c65e700-cc05-11ea-98b0-f34416bf32f9.png)

- [x] https://github.com/threefoldfoundation/info_gridmanual/issues/134 Windows docker setup steps do not match latest docker for windows version

- [x] https://github.com/threefoldfoundation/info_gridmanual/issues/135 3SDK for windows install suddenly talks about 3bot Connect words and links to a page that has zero info on 3bot connect words.

- [ ] https://github.com/threefoldtech/jumpscaleX_core/issues/908 3SDK binary on windows is flagged on both chrome and windows level

- [x] https://github.com/threefoldfoundation/info_gridmanual/issues/136 3botconnect is suddenly required without any previous mention or guide/setup

- [x] https://github.com/threefoldfoundation/info_gridmanual/issues/137 When following the farm setup, the user never gets to a working localhost:4000

- [ ] https://github.com/threefoldtech/jumpscaleX_core/issues/909 localhost:4000 certification security warning after "threebot start"

- [ ] https://github.com/threefoldfoundation/info_gridmanual/issues/139 Nowhere in the installation process was it clear that my 3bot connect email should be verified, until it threw an error in localhost:4000

- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/910 "we could not find model" Error when going to settings on localhost:4000 admin dashboard. Using windows 10 SDK

- [x] https://github.com/threefoldfoundation/info_gridmanual/issues/140 farm setup guide tells user to use "wallet manger" to create a wallet, but requires 3botconnect since stellar

**Comment by xmonader** [comment]
All issues related to certificates are resolved https://manual-testnet.threefold.io/#/local_3bot
