### ISSUE TITLE
Marketplace alpha version

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#856]
- [x] [confirm deletion of reservation](https://github.com/threefoldtech/js-sdk/issues/316)
- [x] [check gateway currencies  soon enough](https://github.com/threefoldtech/js-sdk/issues/310)
- [x] [network selection to be a dropdown](https://github.com/threefoldtech/js-sdk/issues/251)
- [x] [hyperlink fix for 3bot](https://github.com/threefoldtech/js-sdk/issues/312)
- [x] [check availability of domains before reserving](https://github.com/threefoldtech/js-sdk/issues/300)
- [x] [generic flist to be changed to generic container](https://github.com/threefoldtech/js-sdk/issues/309)
- [x] [notebooks package installation](https://github.com/threefoldtech/js-sdk/issues/315)
- [x] [code server installation](https://github.com/threefoldtech/js-sdk/issues/314)
- [x] [confusion of close/cancel buttons](https://github.com/threefoldtech/js-sdk/issues/303)
- [x] [show farms with nodes with enough resources](https://github.com/threefoldtech/js-sdk/issues/311)
- [x] [broken farmmgmt package](https://github.com/threefoldtech/js-sdk/issues/313)
- [x] [use explorer related identity in backup actors](https://github.com/threefoldtech/js-sdk/issues/322)

 ## Documentation

- [x] network
- [x] ubuntu
- [x] minio
- [x] k8s
- [x] gitea
- [x] solution expose
- [x] gitea
- [x] domain delegation
- [x] gateway 4to6
- [x] publisher
- [x] personal 3bot
  -  [x] initialization
  -  [x] backup
  -  [x] restore

**Comment by xmonader** [comment]
- marketplace docs deployed using the publisher solution of the marketplace :D https://solutions.tfgw-testnet-01.gateway.tf
- github pages wiki https://threefoldfoundation.github.io/info_manual_tfgrid_testnet/wiki
