### ISSUE TITLE
February bugs & issues part1

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#87]
- [x] [Explorer has slow response times](https://github.com/threefoldtech/rivine/issues/469)
   - [x] Todo: Initial profiling: 2h
- [x] [explorer.threefoldtoken.com and explorer.testnet.threefoldtoken.com down](https://github.com/threefoldfoundation/tfchain/issues/215) (2h)
  - [x] [Zero os node appears to randomly freeze](https://github.com/threefoldtech/0-core/issues/85)
- [x] [Test if failing blockchain bootstrap node also fails using another OS](https://github.com/threefoldfoundation/tfchain/issues/249)
- [x] [Explain rivine Technical details to Weynand](https://github.com/threefoldtech/rivine/issues/464)
- [x] [Arbitrary data count in explorer is wrong](https://github.com/threefoldfoundation/tfchain/issues/293)
- [x] [Web Explorer shows incorrect amounts for 3Bot Refund Outputs](https://github.com/threefoldfoundation/tfchain/issues/306)
- [x] Rivine travis tests are broken
