### ISSUE TITLE
tft-erc20 fixes

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#88]
- [x] [eth network not syncing in  a network namespace](https://github.com/threefoldfoundation/tfchain/issues/277)
- [x] [syncing fails if there are no eth peers and a block contains an eth tx](https://github.com/threefoldfoundation/tfchain/issues/272)
- [x] [retry failed transaction if bridge has no eth peers](https://github.com/threefoldfoundation/tfchain/issues/273)
- [x] [Make the withdraw functional in the demo/test webapp](https://github.com/threefoldfoundation/tfchain/issues/287)
- [x] [Fix contract withdrawing](https://github.com/threefoldfoundation/tfchain/issues/286)
- [x] [Change bridge logigng](https://github.com/threefoldfoundation/tfchain/issues/284)
- [x] [Possibility to give the erc20 bridge eth bootnodes on the commandline](https://github.com/threefoldfoundation/tfchain/issues/279)
- [x] [Converting TFT to ERC20 failed ](https://github.com/threefoldfoundation/tfchain/issues/285) 
- [x] [not possible to list the registered erc20 withdrawal adresses using tfchaind/tfchainc](https://github.com/threefoldfoundation/tfchain/issues/291)
- [x] [tfchainc wallet send erc20address does not return the used address and the generated erc20 address](https://github.com/threefoldfoundation/tfchain/issues/290)
- [x] [the withdraw modal window in the erc20 exchange example does not close after pressing withdraw](https://github.com/threefoldfoundation/tfchain/issues/289)
- [x] [tfchainc erc20 commands output json while human is the default](https://github.com/threefoldfoundation/tfchain/issues/288)
- [x] [ethvalidation does not accept all possible withdrawals](https://github.com/threefoldfoundation/tfchain/issues/294)
- [x] [ethvalidation: Creating past withdraw event iterator failed](https://github.com/threefoldfoundation/tfchain/issues/302)

**Comment by robvanmieghem** [comment]
follow up story: https://github.com/threefoldtech/home/issues/136
