### ISSUE TITLE
board call preparation (3bot/marketplace)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#882]
- [x] deploy3bot.grid.tf https://github.com/threefoldtech/js-sdk/issues/725
- [x] demo.grid.tf, demo2.grid.tf https://github.com/threefoldtech/js-sdk/issues/738
- [x] remove 3bot from infra solutions https://github.com/threefoldtech/js-sdk/issues/727
- [x] about in solutions cards https://github.com/threefoldtech/js-sdk/issues/731
- [x] testnet identity to be the default on provisioned 3bots https://github.com/threefoldtech/js-sdk/issues/728
- [x] using all farms instead of just freefarm https://github.com/threefoldtech/js-sdk/issues/724 (reverted because of mazraa performance)
- [x] terms and conditions https://github.com/threefoldtech/js-sdk/issues/718 (3bot, demo, deployer)
- [x] disclaimer https://github.com/threefoldtech/js-sdk/issues/717 (3bot, demo, deployer) 
- [x] manual https://github.com/threefoldtech/js-sdk/issues/752 (3bot, demo, deployer) 
- [x] downgrade cryptography package https://github.com/threefoldtech/js-sdk/issues/758
- [x] autobackup error https://github.com/threefoldtech/js-sdk/issues/763
- [x] show indication how to restart chatflow after error https://github.com/threefoldtech/js-sdk/issues/723
- [x] configure over provisioning, test certs in settings https://github.com/threefoldtech/js-sdk/issues/739
- [x] improve domain delegation, custom domains docs https://github.com/threefoldtech/js-sdk/issues/732
- [x] solution expose hardening https://github.com/threefoldtech/js-sdk/issues/729
- [x] rename infrastructure solutions to solutions https://github.com/threefoldtech/js-sdk/issues/728
- [x] rename minio to S3 storage https://github.com/threefoldtech/js-sdk/issues/721 (more occurances needs to be updated)

**Comment by hossnys** [comment]
all listed issues are done and verified
