### ISSUE TITLE
Grid deployment issues and enhancements

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/home#883]
During the deployment of flists we encountered some blocking issues:
- [x] https://github.com/threefoldtech/js-sdk/issues/777 define reservation times on network reservation
- [ ] https://github.com/threefoldtech/js-sdk/issues/780 killing of random processes

There is also room for improvement on:
- [ ] https://github.com/threefoldtech/js-sdk/issues/772 Routing on host/flist name
- [ ] https://github.com/threefoldtech/js-sdk/issues/775 Entering environment variables
- [x] https://github.com/threefoldtech/js-sdk/issues/776 Http vs https in the end screen of deployment
