### ISSUE TITLE
tft-erc20 testnet bridge deployment

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#89]
- [x] Deploy contracts to Ropsten network (4h)
- [x] [publish 1.1.2 rc1](https://github.com/threefoldfoundation/tfchain/issues/268) (4h)
- [x] [rework flist release targets](https://github.com/threefoldfoundation/tfchain/issues/282)
- [x] Run a testnet bridge on Rob's server for testing purposes
- [x] [Deployment templates for bridge daemon](https://github.com/threefoldtech/home/issues/79) (1d)
- [x]  [Reset tf chain testnet](https://github.com/threefoldfoundation/tfchain/issues/269) (2d)
