### ISSUE TITLE
digital.me 0-robot templates for ubuntu / zos-gw

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#9]
## Description

All templates required for a person to deploy ubuntu on top of the primitive services of the TF Grid.

- ubuntu
    - ubuntu in VM directly (ub 16.04/ub18.04) with params
- zos-vm
    - zerotier inside the vm
- zos-gw
    - get your own ZOS-gw, connect to zerotier as used in zos or ubuntu

## Requirements

- provisioning with nothing more as using the primitives of TF Grid.
- some basic monitoring

## deliverables

- good documentation
- the templates
- some test scripts

## remarks

- the templates on https://github.com/Jumpscale/digital_me

## tasks (TODO)

- [ ] [templates for 0-OS gateway](https://github.com/Jumpscale/digital_me/issues/4)
- [x] [templates for VM](https://github.com/Jumpscale/digital_me/issues/3)
- [x] https://github.com/Jumpscale/digital_me/issues/2

## Kanban
https://waffle.io/Zero-OS/home?source=Jumpscale%2Fdigital_me&milestone=0.1.0
