### ISSUE TITLE
3bot deployer for 2.3 (development_3botdeployer)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#906]
- [x] 3bot website overview https://github.com/threefoldtech/js-sdk/issues/1412
- [x] 3bot plan option https://github.com/threefoldtech/js-sdk/issues/1341
- [x] 3bot deployment location https://github.com/threefoldtech/js-sdk/issues/1415
- [x] escalation emails configurations https://github.com/threefoldtech/js-sdk/issues/1413
- [x] identity usage https://github.com/threefoldtech/js-sdk/issues/1416
   - [x] parameterizing zos https://github.com/threefoldtech/js-sdk/issues/1334
- [x] 3bot to have a mainnet wallet and ask user to fund it https://github.com/threefoldtech/js-sdk/issues/1414
- [x] backup ~/.ssh dir https://github.com/threefoldtech/js-sdk/issues/1376
- [x] option to autoextend pools https://github.com/threefoldtech/js-sdk/issues/1337

specs see: https://github.com/threefoldtech/home/blob/master/specs/3bot_221.md

**Comment by despiegk** [comment]
need to review the specs, I want to make sure we are aligned

**Comment by xmonader** [comment]
deplyoed service on: deploy3bot.testnet.grid.tf/

**Comment by Dina-Abd-Elrahman** [comment]
## 3Bot:

**choose where to host your 3bot**

![ff](https://user-images.githubusercontent.com/21218053/98269691-b78da180-1f96-11eb-9028-a5319f5ff1f3.png)
![ff](https://user-images.githubusercontent.com/21218053/98269735-cb390800-1f96-11eb-9694-819cfa946a40.png)
![ff](https://user-images.githubusercontent.com/21218053/98269930-04717800-1f97-11eb-9363-d4a5f2ece64e.png)
![ff](https://user-images.githubusercontent.com/21218053/98270071-2cf97200-1f97-11eb-8703-ee877868a51a.png)

**Choose size**

![ff](https://user-images.githubusercontent.com/21218053/98269433-6382bd00-1f96-11eb-8fc0-2edf50cb2ee1.png)

**Comment by Dina-Abd-Elrahman** [comment]
**UI in 3bot deployer**

![ff](https://user-images.githubusercontent.com/21218053/98272285-98444380-1f99-11eb-9d49-41125a2097d9.png)

**Comment by Dina-Abd-Elrahman** [comment]
![dd](https://user-images.githubusercontent.com/21218053/98272754-1acd0300-1f9a-11eb-9683-aeb6423308fb.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/98274457-1ace0280-1f9c-11eb-9742-ad74eb0f9155.png)
![ff1](https://user-images.githubusercontent.com/21218053/98274352-feca6100-1f9b-11eb-8b2c-774003d02cdc.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/98275235-19e9a080-1f9d-11eb-9741-441ce67680e6.png)
![ff](https://user-images.githubusercontent.com/21218053/98275309-2cfc7080-1f9d-11eb-9933-67cbea7c0c27.png)
