### ISSUE TITLE
TLS certificates for 3bots

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#909]
A story addressing ratelimits for let's encrypt  #875  #904  #905

- [x] zerossl paid subscription
- [x] poc for acme server  https://github.com/threefoldtech/home/issues/905
- [ ] move acme server repo to threefoldtech https://github.com/threefoldtech/tf-acmeserver https://github.com/threefoldtech/tf-acmeserver/issues/1
- [ ] update redis plugin (https://github.com/xmonader/coredns-redis/commit/c13da9e076854fcc6f4eb720264984c35d1e900d) once agreed on should be on coredns-redis https://github.com/threefoldtech/coredns-redis
- [ ] update python sal with CNAME helper
- [ ] enable http01 validation acmeserver/certbots https://github.com/threefoldtech/tf-acmeserver/issues/2
- [ ] cname validation zerossl rest / acme server 
- [ ] Add more record types https://github.com/threefoldtech/tfgateway/issues/41 (needed if we go with workloads way)
- [ ] allow nested subdomains https://github.com/threefoldtech/tfgateway/issues/43 (needed if we go with workloads way)

**Comment by robvanmieghem** [comment]
There already is an issue for this: https://github.com/threefoldtech/home/issues/902.
I also thought we agreed not to go for the workloads way yesterday but with cname validation records in a dns in the acme server. I added some of the todo's in the original issue and some in the issue for the acme server: https://github.com/threefoldtech/home/issues/905

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/home/issues/905
