### ISSUE TITLE
tfchain improvements and fixes

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#91]
- [x] [command outputs in the atomic swap example are slightly outdated](https://github.com/threefoldfoundation/tfchain/issues/122)
- [x] [explorer ui release target in makefile is not cross platform](https://github.com/threefoldfoundation/tfchain/issues/197)
- [x] [unclear documentation for devnet (development) setup](https://github.com/threefoldfoundation/tfchain/issues/219)
