### ISSUE TITLE
Create Gedis actors for capacity reservation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#94]
![threefold tech website](https://user-images.githubusercontent.com/303164/51168985-07bfdf00-18ab-11e9-8238-472d07345373.png)

We need Gedis actors to implement this flow:
- [ ] [Actor between User and 3bot, to select what primitives to reserve](https://github.com/threefoldtech/digitalmeX/issues/12)
- [ ] [Actor between User 3Bot and Bootstrap 3Bot to send reservation requests](https://github.com/threefoldtech/digitalmeX/issues/13)
- [ ] Logic for capacity planning in Bootstrap 3Bot
- [ ] [Actor between Node Zrobot and User 3Bot](https://github.com/threefoldtech/digitalmeX/issues/14)
